-- ═══════════════════════════════════════════════════════════════════════════
-- DraftFor20 · 0019 · billing writes, and the manual grant
--
-- Stripe never talks to Postgres. Our webhook route verifies Stripe's
-- signature, works out what changed, and calls ONE function here with a
-- shared secret. That keeps the service-role key out of the project (see the
-- README: it is not used by this app and must not be added) while still
-- letting a request with no user session write to somebody's profile.
--
-- The secret is generated by this migration, lives in df20_config, and is
-- copied into DF20_BILLING_SECRET on the server. It can only move a
-- subscription date. Leaking it costs a wrongly-granted month, not a
-- database.
-- ═══════════════════════════════════════════════════════════════════════════

insert into public.df20_config (key, value)
values ('billing_write_secret', encode(gen_random_bytes(24), 'hex'))
on conflict (key) do nothing;

-- Stripe retries. Extending a Game Night Pass by 24 hours is the one
-- operation here that is not naturally idempotent, so every event is
-- recorded by id and a repeat is a no-op.
create table if not exists public.billing_events (
  event_id     text primary key,
  kind         text,
  processed_at timestamptz not null default now()
);
alter table public.billing_events enable row level security;
revoke all on public.billing_events from anon, authenticated;

-- ── the only write path Stripe has ────────────────────────────────────────
create or replace function public.df20_apply_billing_event(
  p_secret          text,
  p_event_id        text,
  p_user_id         uuid,
  p_customer_id     text,
  p_subscription_id text,
  p_status          text,
  p_premium_until   timestamptz,
  p_source          text,
  p_extend_hours    int default null
) returns jsonb language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_expected text; v_id uuid; v_until timestamptz; v_rows int;
begin
  select value into v_expected from public.df20_config where key = 'billing_write_secret';
  if v_expected is null or p_secret is null or p_secret <> v_expected then
    raise exception 'DF20_NOT_AUTHORISED';
  end if;

  if p_source is not null and p_source not in
     ('stripe_subscription','admin_grant','game_night_pass') then
    raise exception 'DF20_BAD_SOURCE';
  end if;

  -- who this is about: the id we put in the checkout session first, the
  -- customer we stored second. Never an email — those change.
  if p_user_id is not null then
    select id into v_id from public.profiles where id = p_user_id;
  end if;
  if v_id is null and p_customer_id is not null then
    select id into v_id from public.profiles where stripe_customer_id = p_customer_id;
  end if;
  if v_id is null then
    return jsonb_build_object('matched', false);
  end if;

  if p_event_id is not null then
    insert into public.billing_events (event_id, kind)
    values (p_event_id, coalesce(p_source, 'stripe'))
    on conflict (event_id) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows = 0 then
      return jsonb_build_object('matched', true, 'duplicate', true);
    end if;
  end if;

  if p_extend_hours is not null then
    -- a pass bought while a subscription is running adds to the end of it,
    -- rather than throwing away time already paid for
    select greatest(coalesce(premium_until, now()), now())
             + make_interval(hours => p_extend_hours)
      into v_until from public.profiles where id = v_id;
  else
    v_until := p_premium_until;
  end if;

  update public.profiles
     set premium_until          = coalesce(v_until, premium_until),
         premium_source         = coalesce(p_source, premium_source),
         subscription_status    = coalesce(p_status, subscription_status),
         stripe_customer_id     = coalesce(p_customer_id, stripe_customer_id),
         stripe_subscription_id = coalesce(p_subscription_id, stripe_subscription_id),
         updated_at             = now()
   where id = v_id;

  return jsonb_build_object('matched', true, 'user_id', v_id,
                            'premium_until', to_jsonb(v_until));
end $$;
revoke all on function public.df20_apply_billing_event(text,text,uuid,text,text,text,timestamptz,text,int)
  from anon, authenticated;

-- revoke outright: a subscription deleted mid-period, a chargeback
create or replace function public.df20_revoke_premium(
  p_secret text, p_event_id text, p_customer_id text, p_status text
) returns jsonb language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_expected text; v_id uuid;
begin
  select value into v_expected from public.df20_config where key = 'billing_write_secret';
  if v_expected is null or p_secret is null or p_secret <> v_expected then
    raise exception 'DF20_NOT_AUTHORISED';
  end if;

  select id into v_id from public.profiles where stripe_customer_id = p_customer_id;
  if v_id is null then return jsonb_build_object('matched', false); end if;

  if p_event_id is not null then
    insert into public.billing_events (event_id, kind) values (p_event_id, 'revoke')
    on conflict (event_id) do nothing;
  end if;

  -- an admin grant is not Stripe's to cancel
  update public.profiles
     set premium_until = case when premium_source = 'admin_grant' then premium_until else now() end,
         subscription_status = coalesce(p_status, 'canceled'),
         updated_at = now()
   where id = v_id;
  return jsonb_build_object('matched', true, 'user_id', v_id);
end $$;
revoke all on function public.df20_revoke_premium(text,text,text,text) from anon, authenticated;

-- what the checkout route needs before it calls Stripe
create or replace function public.df20_billing_profile(p_secret text, p_user_id uuid)
returns jsonb language plpgsql stable security definer
set search_path = public, pg_temp as $$
declare v_expected text; v_p public.profiles;
begin
  select value into v_expected from public.df20_config where key = 'billing_write_secret';
  if v_expected is null or p_secret is null or p_secret <> v_expected then
    raise exception 'DF20_NOT_AUTHORISED';
  end if;
  select * into v_p from public.profiles where id = p_user_id;
  if not found then return jsonb_build_object('found', false); end if;
  return jsonb_build_object('found', true, 'email', v_p.email,
                            'customer_id', v_p.stripe_customer_id,
                            'premium_until', to_jsonb(v_p.premium_until));
end $$;
revoke all on function public.df20_billing_profile(text, uuid) from anon, authenticated;

-- ── the manual grant, and the small admin screen over it ──────────────────
-- Nobody is an admin until a uuid is put in this row BY HAND. With the row
-- absent, which is how it ships, df20_is_admin() is false for every caller
-- including the person who wrote this, and /admin renders nothing.
create or replace function public.df20_is_admin()
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.df20_config c,
                  unnest(string_to_array(c.value, ',')) u
     where c.key = 'admin_user_ids'
       and (select auth.uid()) is not null
       and btrim(u) = (select auth.uid())::text)
$$;
grant execute on function public.df20_is_admin() to anon, authenticated;

create or replace function public.admin_list_profiles(p_query text default null)
returns jsonb language plpgsql stable security definer
set search_path = public, pg_temp as $$
declare v_q text;
begin
  if not public.df20_is_admin() then raise exception 'DF20_NOT_AUTHORISED'; end if;
  v_q := lower(btrim(coalesce(p_query, '')));

  return coalesce((
    select jsonb_agg(x order by x->>'created_at' desc) from (
      select jsonb_build_object(
               'id', p.id, 'email', p.email, 'display_name', p.display_name,
               'created_at', p.created_at,
               'premium_until', p.premium_until,
               'premium_source', p.premium_source,
               'subscription_status', p.subscription_status,
               'active', coalesce(p.premium_until > now(), false)) as x
        from public.profiles p
       where v_q = ''
          or lower(coalesce(p.email, '')) like '%' || v_q || '%'
          or lower(coalesce(p.display_name, '')) like '%' || v_q || '%'
       order by p.created_at desc
       limit 100) s), '[]'::jsonb);
end $$;
grant execute on function public.admin_list_profiles(text) to authenticated;

-- p_days <= 0 revokes. Everything else is identical to what a paid
-- subscription writes, which is the whole point: the app cannot tell them
-- apart because it only ever reads premium_until.
create or replace function public.admin_set_premium(p_user_id uuid, p_days int)
returns jsonb language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_until timestamptz;
begin
  if not public.df20_is_admin() then raise exception 'DF20_NOT_AUTHORISED'; end if;
  if p_days is null then raise exception 'DF20_BAD_INPUT'; end if;

  if p_days <= 0 then
    update public.profiles
       set premium_until = null, premium_source = null,
           subscription_status = null, updated_at = now()
     where id = p_user_id;
    return jsonb_build_object('user_id', p_user_id, 'active', false);
  end if;

  v_until := now() + make_interval(days => least(p_days, 3650));
  update public.profiles
     set premium_until = v_until, premium_source = 'admin_grant',
         subscription_status = 'admin', updated_at = now()
   where id = p_user_id;
  return jsonb_build_object('user_id', p_user_id, 'active', true,
                            'premium_until', to_jsonb(v_until));
end $$;
grant execute on function public.admin_set_premium(uuid, int) to authenticated;
