-- ═══════════════════════════════════════════════════════════════════════════
-- DraftFor20 · 0031 · five more anime casts, with portraits
--
-- GENERATED by scripts/build-anime-seed.mjs. Re-run that rather than editing
-- the lists below; names and URLs are positional, and hand editing one
-- without the other slides every later picture onto the wrong character.
--
-- Same shape and same reasoning as 0029 (One Piece): seeded from MyAnimeList
-- rather than resolved from Wikipedia, because Wikipedia redirects most of a
-- cast to a group article and hands several characters the same photograph.
--
-- Depends on 0029 for df20_seed_category(text,text[],text[],text[]) and for
-- the MyAnimeList host on the image allowlist. df20_clean_image_url is
-- re-declared below anyway so this file is correct applied on its own — the
-- df20_clean_logo_url outage was exactly a caller split from its dependency
-- across two migrations.
--
-- Re-runnable. Every seed upserts by normalised name and refreshes portraits.
-- ═══════════════════════════════════════════════════════════════════════════

create or replace function public.df20_clean_image_url(p_in text)
returns text language plpgsql immutable
set search_path = public, pg_temp as $$
declare v text;
begin
  v := btrim(coalesce(p_in, ''));
  if length(v) = 0 or length(v) > 600 then return null; end if;
  if v !~ '^https://' then return null; end if;
  if v !~* '^https://(upload\.wikimedia\.org|commons\.wikimedia\.org|coverartarchive\.org|covers\.openlibrary\.org|cdn\.myanimelist\.net|media\.kitsu\.app)/' then
    return null;
  end if;
  if v ~ '[[:cntrl:]"''<>]' then return null; end if;
  return v;
end $$;

-- ── Jujutsu Kaisen Characters · 28 items
select public.df20_seed_category(
  'Jujutsu Kaisen Characters',
  string_to_array($it$Satoru Gojo
Yuji Itadori
Megumi Fushiguro
Nobara Kugisaki
Sukuna
Suguru Geto
Yuta Okkotsu
Kento Nanami
Maki Zenin
Toge Inumaki
Panda
Aoi Todo
Toji Fushiguro
Kenjaku
Mahito
Choso
Yuki Tsukumo
Kasumi Miwa
Rika Orimoto
Kinji Hakari
Hajime Kashimo
Hiromi Higuruma
Naoya Zenin
Ryu Ishigori
Takako Uro
Fumihiko Takaba
Ui Ui
Mahoraga$it$, E'\n'),
  string_to_array($im$https://media.kitsu.app/character/105898/image/8a8a441392fe5191c2449460e7338ce6.jpg
https://media.kitsu.app/character/105902/image/7fddba940feccb98fbc613fce4fe2a8e.jpg
https://media.kitsu.app/character/105901/image/762b0293d9cd5de95289ea8a9b072b9e.jpg
https://media.kitsu.app/character/105903/image/293753a40af0f34df05532a4f413724d.jpg
https://media.kitsu.app/character/105906/image/de1a29b96b9a8d7eddb6940249d71cd8.jpg
https://media.kitsu.app/character/105899/image/34c2f1977f3e2e61bf6ad8bda436f1a8.jpg
https://media.kitsu.app/character/105900/image/c18c5241b9bc03f730db4f8eee567edb.jpg
https://media.kitsu.app/character/105910/image/f41a11d9bd5ec962b1db4ae8927f38db.jpg
https://media.kitsu.app/character/105909/image/978c0b75541db15e14d9c7f12ae2b681.jpg
https://media.kitsu.app/character/105920/image/20916dd564c1081a4c5e492e9f342776.jpg
https://media.kitsu.app/character/105911/image/8f3df4c97e949d39277a12fd421164b6.jpg
https://media.kitsu.app/character/105929/image/87de341454cec9433a980298b2fb97f2.jpg
https://media.kitsu.app/character/105905/image/d2a5b01f4b2b1a545c9d39f61381b887.jpg
https://media.kitsu.app/character/105904/image/c63ccde661eaad1a7bace91a91f4e97e.jpg
https://media.kitsu.app/character/105912/image/f93eadaeb425d08c3d32622349eaa6ff.jpg
https://media.kitsu.app/character/105908/image/163db31de25c58d1bfeaeb06a3008808.jpg
https://media.kitsu.app/character/105907/image/550ebc7b5ac77a22b0a1eb6f64e7ab2d.jpg
https://media.kitsu.app/character/105930/image/29e1a0120c641b5c6a7acb6e7dac1552.jpg
https://media.kitsu.app/character/105919/image/229e4c5d6069e29b845cab425be838a2.jpg
https://media.kitsu.app/character/105921/image/f420358849a09282be9c19ef0dde4ab1.jpg
https://media.kitsu.app/character/105922/image/2a241b9efbb1dac2a7e48b7884440d88.jpg
https://media.kitsu.app/character/105923/image/add52c63e9c63252f2f90f31140b193a.jpg
https://media.kitsu.app/character/105924/image/a543689770fb4b87a534808ac76f1f29.jpg
https://media.kitsu.app/character/105925/image/55c8ac4ab716915227163ada3417ee20.jpg
https://media.kitsu.app/character/105926/image/f4bae31c0f91191bb50af952874d5f97.jpg
https://media.kitsu.app/character/105994/image/7b4c4dbe02d0bb23de5db2def2bbc347.jpg
https://media.kitsu.app/character/105995/image/1405064d9647328bc3407c0ca93bbfc0.png
https://media.kitsu.app/character/105993/image/b6122dbc829add43c4ecef04e89bdcc7.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[28]));

select public.df20_add_alias('Jujutsu Kaisen Characters',
  array['jujutsu kaisen', 'jjk', 'jujutsu kaisen cast']);

-- ── Dragon Ball Z Characters · 65 items
select public.df20_seed_category(
  'Dragon Ball Z Characters',
  string_to_array($it$Goku
Vegeta
Gohan
Piccolo
Krillin
Frieza
Cell
Majin Buu
Trunks
Future Trunks
Goten
Bulma
Chi-Chi
Master Roshi
Yamcha
Tien
Chiaotzu
Android 16
Android 17
Android 18
Android 19
Dr. Gero
Nappa
Raditz
Bardock
King Vegeta
Zarbon
Dodoria
Captain Ginyu
Recoome
Burter
Jeice
Guldo
King Cold
Babidi
Dabura
Spopovich
Videl
Mr. Satan
Supreme Kai
Kibito
Dende
Nail
Kami
Mr. Popo
King Kai
Korin
Yajirobe
Oolong
Puar
Uub
Pan
Shenron
Porunga
Mercenary Tao
King Piccolo
Garlic Jr.
Ox-King
Fortuneteller Baba
Launch
Marron
Paikuhan
Yakon
Pui Pui
Gine$it$, E'\n'),
  string_to_array($im$https://media.kitsu.app/characters/images/4119/original.jpg
https://media.kitsu.app/characters/images/4196/original.jpg
https://media.kitsu.app/characters/images/4231/original.jpg
https://media.kitsu.app/characters/images/4121/original.jpg
https://media.kitsu.app/characters/images/4115/original.jpg
https://media.kitsu.app/characters/images/4209/original.jpg
https://media.kitsu.app/characters/images/4210/original.jpg
https://media.kitsu.app/characters/images/4200/original.jpg
https://media.kitsu.app/characters/images/4199/original.jpg
https://media.kitsu.app/characters/images/86951/original.jpg
https://media.kitsu.app/characters/images/4233/original.jpg
https://media.kitsu.app/characters/images/4117/original.jpg
https://media.kitsu.app/characters/images/4128/original.jpg
https://media.kitsu.app/characters/images/4118/original.jpg
https://media.kitsu.app/characters/images/4116/original.jpg
https://media.kitsu.app/characters/images/4157/original.jpg
https://media.kitsu.app/characters/images/4156/original.jpg
https://media.kitsu.app/characters/images/10340/original.jpg
https://media.kitsu.app/characters/images/4206/original.jpg
https://media.kitsu.app/characters/images/4211/original.jpg
https://media.kitsu.app/characters/images/4214/original.jpg
https://media.kitsu.app/characters/images/4205/original.jpg
https://media.kitsu.app/characters/images/4213/original.jpg
https://media.kitsu.app/characters/images/10358/original.jpg
https://media.kitsu.app/characters/images/10349/original.jpg
https://media.kitsu.app/characters/images/4221/original.jpg
https://media.kitsu.app/characters/images/10347/original.jpg
https://media.kitsu.app/characters/images/10360/original.jpg
https://media.kitsu.app/characters/images/10353/original.jpg
https://media.kitsu.app/characters/images/10357/original.jpg
https://media.kitsu.app/characters/images/10354/original.jpg
https://media.kitsu.app/characters/images/10356/original.jpg
https://media.kitsu.app/characters/images/10355/original.jpg
https://media.kitsu.app/characters/images/10372/original.jpg
https://media.kitsu.app/characters/images/10350/original.jpg
https://media.kitsu.app/characters/images/10351/original.jpg
https://media.kitsu.app/characters/images/10345/original.jpg
https://media.kitsu.app/characters/images/4203/original.jpg
https://media.kitsu.app/characters/images/4219/original.jpg
https://media.kitsu.app/characters/images/10352/original.jpg
https://media.kitsu.app/characters/images/10366/original.jpg
https://media.kitsu.app/characters/images/4215/original.jpg
https://media.kitsu.app/characters/images/10359/original.jpg
https://media.kitsu.app/characters/images/4159/original.jpg
https://media.kitsu.app/characters/images/4158/original.jpg
https://media.kitsu.app/characters/images/4212/original.jpg
https://media.kitsu.app/characters/images/4161/original.jpg
https://media.kitsu.app/characters/images/4125/original.jpg
https://media.kitsu.app/characters/images/4130/original.jpg
https://media.kitsu.app/characters/images/4120/original.jpg
https://media.kitsu.app/characters/images/4220/original.jpg
https://media.kitsu.app/characters/images/4197/original.jpg
https://media.kitsu.app/characters/images/4160/original.jpg
https://media.kitsu.app/characters/images/10363/original.jpg
https://media.kitsu.app/characters/images/4145/original.jpg
https://media.kitsu.app/characters/images/4165/original.jpg
https://media.kitsu.app/characters/images/10348/original.jpg
https://media.kitsu.app/characters/images/4122/original.jpg
https://media.kitsu.app/characters/images/4194/original.jpg
https://media.kitsu.app/characters/images/4129/original.jpg
https://media.kitsu.app/characters/images/4202/original.jpg
https://media.kitsu.app/characters/images/10364/original.jpg
https://media.kitsu.app/characters/images/10374/original.jpg
https://media.kitsu.app/characters/images/10362/original.jpg
https://media.kitsu.app/characters/images/41540/original.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[65]));

select public.df20_add_alias('Dragon Ball Z Characters',
  array['dragon ball z', 'dragonball z', 'dbz', 'dragon ball']);

-- ── My Hero Academia Characters · 66 items
select public.df20_seed_category(
  'My Hero Academia Characters',
  string_to_array($it$Izuku Midoriya
Katsuki Bakugo
Shoto Todoroki
Ochaco Uraraka
Tenya Iida
All Might
Shota Aizawa
Tsuyu Asui
Eijiro Kirishima
Denki Kaminari
Momo Yaoyorozu
Kyoka Jiro
Fumikage Tokoyami
Mina Ashido
Hanta Sero
Mezo Shoji
Rikido Sato
Koji Koda
Toru Hagakure
Yuga Aoyama
Mashirao Ojiro
Minoru Mineta
All For One
Tomura Shigaraki
Dabi
Himiko Toga
Kurogiri
Stain
Overhaul
Twice
Muscular
Mr. Compress
Spinner
Magne
Endeavor
Hawks
Best Jeanist
Mirko
Edgeshot
Kamui Woods
Mt. Lady
Present Mic
Midnight
Recovery Girl
Principal Nezu
Sir Nighteye
Gran Torino
Mirio Togata
Nejire Hado
Tamaki Amajiki
Eri
Mei Hatsume
Itsuka Kendo
Neito Monoma
Tetsutetsu Tetsutetsu
Hitoshi Shinso
Fuyumi Todoroki
Nana Shimura
Inko Midoriya
Mitsuki Bakugo
Ibara Shiozaki
Setsuna Tokage
Pony Tsunotori
Inasa Yoarashi
Camie Utsushimi
Nomu$it$, E'\n'),
  string_to_array($im$https://media.kitsu.app/characters/images/61663/original.jpg
https://media.kitsu.app/characters/images/61661/original.jpg
https://media.kitsu.app/characters/images/61664/original.jpg
https://media.kitsu.app/characters/images/61665/original.jpg
https://media.kitsu.app/characters/images/61662/original.jpg
https://media.kitsu.app/characters/images/61660/original.jpg
https://media.kitsu.app/characters/images/61666/original.jpg
https://media.kitsu.app/characters/images/61669/original.jpg
https://media.kitsu.app/characters/images/61676/original.jpg
https://media.kitsu.app/characters/images/61674/original.jpg
https://media.kitsu.app/characters/images/61688/original.jpg
https://media.kitsu.app/characters/images/61673/original.jpg
https://media.kitsu.app/characters/images/61687/original.jpg
https://media.kitsu.app/characters/images/61668/original.jpg
https://media.kitsu.app/characters/images/61685/original.jpg
https://media.kitsu.app/characters/images/61686/original.jpg
https://media.kitsu.app/characters/images/61684/original.jpg
https://media.kitsu.app/characters/images/61677/original.jpg
https://media.kitsu.app/characters/images/61672/original.jpg
https://media.kitsu.app/characters/images/61667/original.jpg
https://media.kitsu.app/characters/images/61681/original.jpg
https://media.kitsu.app/characters/images/61679/original.jpg
https://media.kitsu.app/characters/images/82393/original.jpg
https://media.kitsu.app/characters/images/87109/original.jpg
https://media.kitsu.app/characters/images/89171/original.jpg
https://media.kitsu.app/characters/images/78153/original.jpg
https://media.kitsu.app/characters/images/85839/original.jpg
https://media.kitsu.app/characters/images/90839/original.jpg
https://media.kitsu.app/characters/images/103007/original.jpg
https://media.kitsu.app/characters/images/95686/original.jpg
https://media.kitsu.app/characters/images/98279/original.jpg
https://media.kitsu.app/characters/images/98283/original.jpg
https://media.kitsu.app/characters/images/98079/original.jpg
https://media.kitsu.app/characters/images/98282/original.jpg
https://media.kitsu.app/characters/images/94227/original.jpg
https://media.kitsu.app/characters/images/105807/original.jpg
https://media.kitsu.app/characters/images/104274/original.jpg
https://media.kitsu.app/character/105805/image/7ba1fa0db802478d1ae57bda3d85ffc3.jpg
https://media.kitsu.app/characters/images/104271/original.jpg
https://media.kitsu.app/characters/images/61675/original.jpg
https://media.kitsu.app/characters/images/61680/original.jpg
https://media.kitsu.app/characters/images/61682/original.jpg
https://media.kitsu.app/characters/images/70008/original.jpg
https://media.kitsu.app/characters/images/61683/original.jpg
https://media.kitsu.app/characters/images/80402/original.jpg
https://media.kitsu.app/characters/images/98275/original.jpg
https://media.kitsu.app/characters/images/70274/original.jpg
https://media.kitsu.app/characters/images/103817/original.jpg
https://media.kitsu.app/characters/images/104284/original.jpg
https://media.kitsu.app/characters/images/104285/original.jpg
https://media.kitsu.app/characters/images/102018/original.jpg
https://media.kitsu.app/characters/images/81809/original.png
https://media.kitsu.app/characters/images/76532/original.jpg
https://media.kitsu.app/characters/images/63613/original.jpg
https://media.kitsu.app/characters/images/95066/original.jpg
https://media.kitsu.app/characters/images/85271/original.jpg
https://media.kitsu.app/characters/images/90502/original.jpg
https://media.kitsu.app/characters/images/76471/original.jpg
https://media.kitsu.app/characters/images/61678/original.jpg
https://media.kitsu.app/characters/images/96320/original.jpg
https://media.kitsu.app/characters/images/76346/original.jpg
https://media.kitsu.app/characters/images/84566/original.jpg
https://media.kitsu.app/characters/images/86276/original.jpg
https://media.kitsu.app/characters/images/87462/original.jpg
https://media.kitsu.app/characters/images/104290/original.jpg
https://media.kitsu.app/characters/images/84043/original.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[66]));

select public.df20_add_alias('My Hero Academia Characters',
  array['my hero academia', 'mha', 'boku no hero academia', 'bnha']);

-- ── Naruto Characters · 60 items
select public.df20_seed_category(
  'Naruto Characters',
  string_to_array($it$Naruto Uzumaki
Itachi Uchiha
Kakashi Hatake
Sasuke Uchiha
Shikamaru Nara
Jiraiya
Gaara
Hinata Hyuga
Minato Namikaze
Pain
Rock Lee
Sakura Haruno
Neji Hyuga
Deidara
Orochimaru
Might Guy
Tsunade
Hidan
Temari
Konan
Zabuza Momochi
Kiba Inuzuka
Kurama
Tobirama Senju
Hashirama Senju
Haku
Kisame Hoshigaki
Tenten
Ino Yamanaka
Shino Aburame
Kimimaro
Kabuto Yakushi
Kakuzu
Iruka Umino
Asuma Sarutobi
Konohamaru Sarutobi
Akamaru
Kankuro
Teuchi
Anko Mitarashi
Choji Akimichi
Hanabi Hyuga
Tayuya
Kurenai Yuhi
Zetsu
Hiruzen Sarutobi
Pakkun
Gamatatsu
Gamabunta
Genma Shiranui
Hayate Gekko
Mikoto Uchiha
Shikaku Nara
Gamakichi
Shizune
Tonton
Menma
Dosu Kinuta
Genzo
Kotetsu Hagane$it$, E'\n'),
  string_to_array($im$https://cdn.myanimelist.net/images/characters/2/284121.jpg
https://cdn.myanimelist.net/images/characters/9/284122.jpg
https://cdn.myanimelist.net/images/characters/7/284129.jpg
https://cdn.myanimelist.net/images/characters/9/131317.jpg
https://cdn.myanimelist.net/images/characters/3/131315.jpg
https://cdn.myanimelist.net/images/characters/15/68618.jpg
https://cdn.myanimelist.net/images/characters/10/293375.jpg
https://cdn.myanimelist.net/images/characters/6/278736.jpg
https://cdn.myanimelist.net/images/characters/14/128074.jpg
https://cdn.myanimelist.net/images/characters/8/73473.jpg
https://cdn.myanimelist.net/images/characters/13/433353.jpg
https://cdn.myanimelist.net/images/characters/9/69275.jpg
https://cdn.myanimelist.net/images/characters/2/105538.jpg
https://cdn.myanimelist.net/images/characters/9/131319.jpg
https://cdn.myanimelist.net/images/characters/3/162089.jpg
https://cdn.myanimelist.net/images/characters/16/103576.jpg
https://cdn.myanimelist.net/images/characters/12/523646.jpg
https://cdn.myanimelist.net/images/characters/8/103578.jpg
https://cdn.myanimelist.net/images/characters/13/292452.jpg
https://cdn.myanimelist.net/images/characters/13/158755.jpg
https://cdn.myanimelist.net/images/characters/14/103706.jpg
https://cdn.myanimelist.net/images/characters/11/131217.jpg
https://cdn.myanimelist.net/images/characters/5/232183.jpg
https://cdn.myanimelist.net/images/characters/2/293367.jpg
https://cdn.myanimelist.net/images/characters/10/34809.jpg
https://cdn.myanimelist.net/images/characters/10/103707.jpg
https://cdn.myanimelist.net/images/characters/11/433351.jpg
https://cdn.myanimelist.net/images/characters/16/110946.jpg
https://cdn.myanimelist.net/images/characters/9/60062.jpg
https://cdn.myanimelist.net/images/characters/16/292449.jpg
https://cdn.myanimelist.net/images/characters/13/103598.jpg
https://cdn.myanimelist.net/images/characters/14/82459.jpg
https://cdn.myanimelist.net/images/characters/11/255727.jpg
https://cdn.myanimelist.net/images/characters/10/100216.jpg
https://cdn.myanimelist.net/images/characters/13/82538.jpg
https://cdn.myanimelist.net/images/characters/7/109419.jpg
https://cdn.myanimelist.net/images/characters/6/58197.jpg
https://cdn.myanimelist.net/images/characters/7/68615.jpg
https://cdn.myanimelist.net/images/characters/14/62801.jpg
https://cdn.myanimelist.net/images/characters/8/66177.jpg
https://cdn.myanimelist.net/images/characters/9/105421.jpg
https://cdn.myanimelist.net/images/characters/16/292518.jpg
https://cdn.myanimelist.net/images/characters/10/295205.jpg
https://cdn.myanimelist.net/images/characters/8/103797.jpg
https://cdn.myanimelist.net/images/characters/11/76260.jpg
https://cdn.myanimelist.net/images/characters/2/68520.jpg
https://cdn.myanimelist.net/images/characters/13/54922.jpg
https://cdn.myanimelist.net/images/characters/13/62776.jpg
https://cdn.myanimelist.net/images/characters/6/70846.jpg
https://cdn.myanimelist.net/images/characters/3/104664.jpg
https://cdn.myanimelist.net/images/characters/10/104665.jpg
https://cdn.myanimelist.net/images/characters/6/103949.jpg
https://cdn.myanimelist.net/images/characters/2/100214.jpg
https://cdn.myanimelist.net/images/characters/13/54034.jpg
https://cdn.myanimelist.net/images/characters/3/103794.jpg
https://cdn.myanimelist.net/images/characters/4/218401.jpg
https://cdn.myanimelist.net/images/characters/5/57869.jpg
https://cdn.myanimelist.net/images/characters/14/36354.jpg
https://cdn.myanimelist.net/images/characters/4/66172.jpg
https://cdn.myanimelist.net/images/characters/4/104662.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[60]));

select public.df20_add_alias('Naruto Characters',
  array['naruto', 'naruto characters', 'naruto shippuden', 'hidden leaf']);

-- ── Demon Slayer Characters · 45 items
select public.df20_seed_category(
  'Demon Slayer Characters',
  string_to_array($it$Tanjiro Kamado
Zenitsu Agatsuma
Inosuke Hashibira
Kyojuro Rengoku
Nezuko Kamado
Shinobu Kocho
Giyu Tomioka
Tengen Uzui
Mitsuri Kanroji
Muichiro Tokito
Kanao Tsuyuri
Sanemi Shinazugawa
Obanai Iguro
Yoriichi Tsugikuni
Genya Shinazugawa
Muzan Kibutsuji
Sabito
Gyomei Himejima
Rui
Enmu
Hotaru Haganezuka
Tamayo
Kanae Kocho
Sakonji Urokodaki
Yushiro
Mother Spider Demon
Kagaya Ubuyashiki
Makomo
Ukogi
Susamaru
Aoi Kanzaki
Tanjuro Kamado
Kaigaku
Goto
Kie Kamado
Murata
Hanako Kamado
Kyogai
Nakime
Older Sister Spider Demon
Kiriya Ubuyashiki
Matsuemon Tennoji
Jigoro Kuwajima
Toyo
Hand Demon$it$, E'\n'),
  string_to_array($im$https://cdn.myanimelist.net/images/characters/6/386735.jpg
https://cdn.myanimelist.net/images/characters/10/459689.jpg
https://cdn.myanimelist.net/images/characters/3/329560.jpg
https://cdn.myanimelist.net/images/characters/10/423443.jpg
https://cdn.myanimelist.net/images/characters/2/378254.jpg
https://cdn.myanimelist.net/images/characters/3/386591.jpg
https://cdn.myanimelist.net/images/characters/3/423445.jpg
https://cdn.myanimelist.net/images/characters/16/387706.jpg
https://cdn.myanimelist.net/images/characters/11/514229.jpg
https://cdn.myanimelist.net/images/characters/5/464903.jpg
https://cdn.myanimelist.net/images/characters/2/384712.jpg
https://cdn.myanimelist.net/images/characters/11/556642.jpg
https://cdn.myanimelist.net/images/characters/15/466014.jpg
https://cdn.myanimelist.net/images/characters/12/394870.jpg
https://cdn.myanimelist.net/images/characters/5/390152.jpg
https://cdn.myanimelist.net/images/characters/4/384669.jpg
https://cdn.myanimelist.net/images/characters/8/599194.jpg
https://cdn.myanimelist.net/images/characters/10/550017.jpg
https://cdn.myanimelist.net/images/characters/4/385228.jpg
https://cdn.myanimelist.net/images/characters/16/440983.jpg
https://cdn.myanimelist.net/images/characters/13/379207.jpg
https://cdn.myanimelist.net/images/characters/14/384692.jpg
https://cdn.myanimelist.net/images/characters/16/389355.jpg
https://cdn.myanimelist.net/images/characters/11/382214.jpg
https://cdn.myanimelist.net/images/characters/5/384720.jpg
https://cdn.myanimelist.net/images/characters/4/385242.jpg
https://cdn.myanimelist.net/images/characters/2/387497.jpg
https://cdn.myanimelist.net/images/characters/7/382213.jpg
https://cdn.myanimelist.net/images/characters/11/470329.jpg
https://cdn.myanimelist.net/images/characters/3/379196.jpg
https://cdn.myanimelist.net/images/characters/5/388816.jpg
https://cdn.myanimelist.net/images/characters/9/385444.jpg
https://cdn.myanimelist.net/images/characters/7/508549.jpg
https://cdn.myanimelist.net/images/characters/10/388820.jpg
https://cdn.myanimelist.net/images/characters/3/382215.jpg
https://cdn.myanimelist.net/images/characters/6/388807.jpg
https://cdn.myanimelist.net/images/characters/9/382218.jpg
https://cdn.myanimelist.net/images/characters/6/385328.jpg
https://cdn.myanimelist.net/images/characters/2/551259.jpg
https://cdn.myanimelist.net/images/characters/11/385245.jpg
https://cdn.myanimelist.net/images/characters/6/385248.jpg
https://cdn.myanimelist.net/images/characters/4/494313.jpg
https://cdn.myanimelist.net/images/characters/7/385246.jpg
https://cdn.myanimelist.net/images/characters/13/388819.jpg
https://cdn.myanimelist.net/images/characters/7/385331.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[45]));

select public.df20_add_alias('Demon Slayer Characters',
  array['demon slayer', 'kimetsu no yaiba', 'demon slayer characters']);

-- ── assert every one of them landed with distinct pictures ────────────────
-- Distinct, not merely non-null: the Wikipedia failure mode this whole
-- approach exists to avoid is several characters sharing one group photo,
-- and a count of non-null images would not notice that at all.
do $$
declare c text; v_total int; v_imgs int; v_distinct int;
  v_cats text[] := array['Jujutsu Kaisen Characters', 'Dragon Ball Z Characters', 'My Hero Academia Characters', 'Naruto Characters', 'Demon Slayer Characters'];
begin
  foreach c in array v_cats loop
    select count(*), count(i.image_url), count(distinct i.image_url)
      into v_total, v_imgs, v_distinct
      from public.category_library_items i
      join public.category_library l on l.id = i.library_id
     where l.name_norm = public.df20_norm_category(c);

    if v_total < 30 then
      raise exception 'DF20_ANIME_TOO_SMALL: % has only % items', c, v_total;
    end if;
    if v_imgs < v_total then
      raise exception 'DF20_ANIME_MISSING_IMAGES: % of % items in % have no picture',
        v_total - v_imgs, v_total, c;
    end if;
    if v_distinct < v_total then
      raise exception 'DF20_ANIME_DUPLICATE_IMAGES: % shares % pictures across % items',
        c, v_total - v_distinct, v_total;
    end if;
    raise notice '%: % items, % distinct portraits', c, v_total, v_distinct;
  end loop;
end $$;
