-- ═══════════════════════════════════════════════════════════════════════════
-- DraftFor20 · 0044 · One Piece Characters, with portraits
--
-- GENERATED by scripts/build-onepiece-seed.mjs. Re-run that rather than
-- editing the lists below; the names and the URLs are positional and hand
-- editing one without the other slides every later picture onto the wrong
-- character.
--
-- The first library category to ship with images. 0043 carries image_url the
-- length of the chain (library -> room_pool -> room_deck -> lots), and the
-- leak rule is unchanged: the picture travels exactly where the name travels
-- and reaches a client only when the card is dealt.
--
-- Re-runnable. Both seeds upsert by normalised name.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── the image allowlist gains one host ────────────────────────────────────
-- Everything else about df20_clean_image_url is the 0043 text. MAL portraits
-- are fair-use promotional art, which is the same footing as the non-free
-- Wikipedia infobox leads already allowed, and they are stored as 'nonfree'
-- so a freeOnly policy can drop them as a set.
create or replace function public.df20_clean_image_url(p_in text)
returns text language plpgsql immutable
set search_path = public, pg_temp as $$
declare v text;
begin
  v := btrim(coalesce(p_in, ''));
  if length(v) = 0 or length(v) > 600 then return null; end if;
  if v !~ '^https://' then return null; end if;
  if v !~* '^https://(upload\.wikimedia\.org|commons\.wikimedia\.org|coverartarchive\.org|covers\.openlibrary\.org|cdn\.myanimelist\.net)/' then
    return null;
  end if;
  if v ~ '[[:cntrl:]"''<>]' then return null; end if;
  return v;
end $$;

-- ── seeding a category that has pictures ──────────────────────────────────
-- Four arguments with NO defaults, so the two-argument df20_seed_category
-- survives as a real function rather than becoming an ambiguous call. Same
-- reasoning as the two df20_cache_wikipedia arities in 0043, and the
-- two-argument form is asserted by df20_selfcheck().
--
-- Indexed rather than FOREACH because the arrays are positional: a name that
-- fails df20_clean_text must not shift every following image up by one.
create or replace function public.df20_seed_category(
  p_name text, p_items text[], p_images text[], p_licenses text[]
) returns int language plpgsql security definer
set search_path = public, pg_temp as $fn$
declare v_id uuid; v_clean text; v_img text; v_lic text; v_n int; i int;
begin
  insert into public.category_library (name, name_norm)
  values (p_name, public.df20_norm_category(p_name))
  on conflict (name_norm) do update set name = excluded.name
  returning id into v_id;

  for i in 1 .. coalesce(array_length(p_items, 1), 0) loop
    v_clean := public.df20_clean_text(p_items[i], 60);
    if length(coalesce(v_clean, '')) >= 1 then
      v_img := public.df20_clean_image_url(
                 case when p_images is null or i > coalesce(array_length(p_images, 1), 0)
                      then null else p_images[i] end);
      v_lic := case when p_licenses is null or i > coalesce(array_length(p_licenses, 1), 0)
                    then null else p_licenses[i] end;
      if v_img is null then v_lic := null; end if;      -- keep the pair honest
      if v_lic is not null and v_lic not in ('free', 'nonfree') then v_lic := null; end if;

      -- on conflict UPDATE, not DO NOTHING: re-running has to be able to
      -- refresh a portrait whose URL moved, which DO NOTHING would silently
      -- skip for every name that already existed
      insert into public.category_library_items (library_id, name, image_url, image_license)
      values (v_id, v_clean, v_img, v_lic)
      on conflict (library_id, name)
        do update set image_url = excluded.image_url,
                      image_license = excluded.image_license;
    end if;
  end loop;

  select count(*) into v_n from public.category_library_items where library_id = v_id;
  return v_n;
end $fn$;
revoke all on function public.df20_seed_category(text, text[], text[], text[]) from anon, authenticated;

-- ── One Piece Characters · 80 items ────────────────────────────────
select public.df20_seed_category(
  'One Piece Characters',
  string_to_array($it$Monkey D. Luffy
Roronoa Zoro
Sanji
Nico Robin
Trafalgar Law
Tony Tony Chopper
Nami
Usopp
Portgas D. Ace
Brook
Franky
Charlotte Katakuri
Shanks
Whitebeard
Donquixote Doflamingo
Jinbe
Boa Hancock
Donquixote Rosinante
Yamato
Bon Clay
Dracule Mihawk
Sabo
Carrot
Perona
Buggy
Crocodile
Bartholomew Kuma
Kozuki Oden
Monkey D. Garp
Blackbeard
Silvers Rayleigh
Marco
Aokiji
Bartolomeo
Kizaru
Gol D. Roger
Eustass Kid
Uta
Smoker
Nefertari Vivi
Enel
Fujitora
Akainu
Monkey D. Dragon
Kaido
Rocks D. Xebec
Jewelry Bonney
Senor Pink
Rob Lucci
Vinsmoke Reiju
Koby
Bepo
Hiluluk
Karoo
Emporio Ivankov
Caesar Clown
Big Mom
Loki
Tashigi
Ulti
Monet
Shirahoshi
Chouchou
Laboon
Okiku
Kaku
Koala
Charlotte Pudding
Gaimon
Pandaman
Benn Beckman
Tama
Cavendish
Killer
Gecko Moria
Kung Fu Dugong
Bellemere
Kyros
Ryuma
Fisher Tiger$it$, E'\n'),
  string_to_array($im$https://cdn.myanimelist.net/images/characters/9/310307.jpg
https://cdn.myanimelist.net/images/characters/3/100534.jpg
https://cdn.myanimelist.net/images/characters/5/136769.jpg
https://cdn.myanimelist.net/images/characters/16/363700.jpg
https://cdn.myanimelist.net/images/characters/10/258757.jpg
https://cdn.myanimelist.net/images/characters/3/100536.jpg
https://cdn.myanimelist.net/images/characters/6/59914.jpg
https://cdn.myanimelist.net/images/characters/16/188076.jpg
https://cdn.myanimelist.net/images/characters/2/72220.jpg
https://cdn.myanimelist.net/images/characters/10/161005.jpg
https://cdn.myanimelist.net/images/characters/13/210053.jpg
https://cdn.myanimelist.net/images/characters/8/342776.jpg
https://cdn.myanimelist.net/images/characters/9/307639.jpg
https://cdn.myanimelist.net/images/characters/3/100236.jpg
https://cdn.myanimelist.net/images/characters/5/349513.jpg
https://cdn.myanimelist.net/images/characters/15/307148.jpg
https://cdn.myanimelist.net/images/characters/14/146013.jpg
https://cdn.myanimelist.net/images/characters/13/288038.jpg
https://cdn.myanimelist.net/images/characters/14/490104.jpg
https://cdn.myanimelist.net/images/characters/6/146037.jpg
https://cdn.myanimelist.net/images/characters/7/69747.jpg
https://cdn.myanimelist.net/images/characters/15/131855.jpg
https://cdn.myanimelist.net/images/characters/8/323766.jpg
https://cdn.myanimelist.net/images/characters/15/136777.jpg
https://cdn.myanimelist.net/images/characters/6/69112.jpg
https://cdn.myanimelist.net/images/characters/6/100535.jpg
https://cdn.myanimelist.net/images/characters/2/54820.jpg
https://cdn.myanimelist.net/images/characters/4/433930.jpg
https://cdn.myanimelist.net/images/characters/5/509073.jpg
https://cdn.myanimelist.net/images/characters/2/109536.jpg
https://cdn.myanimelist.net/images/characters/16/141861.jpg
https://cdn.myanimelist.net/images/characters/4/100226.jpg
https://cdn.myanimelist.net/images/characters/9/96167.jpg
https://cdn.myanimelist.net/images/characters/13/249217.jpg
https://cdn.myanimelist.net/images/characters/12/96168.jpg
https://cdn.myanimelist.net/images/characters/3/51747.jpg
https://cdn.myanimelist.net/images/characters/12/146187.jpg
https://cdn.myanimelist.net/images/characters/11/506689.jpg
https://cdn.myanimelist.net/images/characters/5/235841.jpg
https://cdn.myanimelist.net/images/characters/9/298188.jpg
https://cdn.myanimelist.net/images/characters/16/55111.jpg
https://cdn.myanimelist.net/images/characters/14/235827.jpg
https://cdn.myanimelist.net/images/characters/16/306908.jpg
https://cdn.myanimelist.net/images/characters/6/193567.jpg
https://cdn.myanimelist.net/images/characters/4/492819.jpg
https://cdn.myanimelist.net/images/characters/6/619345.jpg
https://cdn.myanimelist.net/images/characters/14/146045.jpg
https://cdn.myanimelist.net/images/characters/16/235809.jpg
https://cdn.myanimelist.net/images/characters/14/71509.jpg
https://cdn.myanimelist.net/images/characters/6/343184.jpg
https://cdn.myanimelist.net/images/characters/11/49289.jpg
https://cdn.myanimelist.net/images/characters/16/51353.jpg
https://cdn.myanimelist.net/images/characters/2/61610.jpg
https://cdn.myanimelist.net/images/characters/3/64158.jpg
https://cdn.myanimelist.net/images/characters/6/81182.jpg
https://cdn.myanimelist.net/images/characters/7/235823.jpg
https://cdn.myanimelist.net/images/characters/14/337166.jpg
https://cdn.myanimelist.net/images/characters/4/593001.jpg
https://cdn.myanimelist.net/images/characters/2/266983.jpg
https://cdn.myanimelist.net/images/characters/8/453421.jpg
https://cdn.myanimelist.net/images/characters/8/235837.jpg
https://cdn.myanimelist.net/images/characters/14/159079.jpg
https://cdn.myanimelist.net/images/characters/2/379992.jpg
https://cdn.myanimelist.net/images/characters/13/235377.jpg
https://cdn.myanimelist.net/images/characters/9/390613.jpg
https://cdn.myanimelist.net/images/characters/12/51463.jpg
https://cdn.myanimelist.net/images/characters/16/391323.jpg
https://cdn.myanimelist.net/images/characters/9/328672.jpg
https://cdn.myanimelist.net/images/characters/11/384783.jpg
https://cdn.myanimelist.net/images/characters/5/190448.jpg
https://cdn.myanimelist.net/images/characters/13/110987.jpg
https://cdn.myanimelist.net/images/characters/2/384729.jpg
https://cdn.myanimelist.net/images/characters/15/280596.jpg
https://cdn.myanimelist.net/images/characters/12/51350.jpg
https://cdn.myanimelist.net/images/characters/2/61709.jpg
https://cdn.myanimelist.net/images/characters/13/155273.jpg
https://cdn.myanimelist.net/images/characters/10/350916.jpg
https://cdn.myanimelist.net/images/characters/2/274449.jpg
https://cdn.myanimelist.net/images/characters/13/530997.jpg
https://cdn.myanimelist.net/images/characters/8/162743.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[80]));

select public.df20_add_alias('One Piece Characters',
  array['one piece', 'onepiece', 'one piece cast', 'straw hats', 'straw hat pirates']);

-- ── assert the pictures actually landed ───────────────────────────────────
-- A silent zero here would mean every portrait failed df20_clean_image_url
-- and the whole category quietly degraded to generated cards.
do $$
declare v_total int; v_imgs int;
begin
  select count(*), count(image_url) into v_total, v_imgs
    from public.category_library_items i
    join public.category_library l on l.id = i.library_id
   where l.name_norm = public.df20_norm_category('One Piece Characters');

  if v_total < 60 then
    raise exception 'DF20_ONEPIECE_TOO_SMALL: % items, need 60 for a 30-slot roster', v_total;
  end if;
  if v_imgs < v_total then
    raise exception 'DF20_ONEPIECE_MISSING_IMAGES: % of % items have no picture',
      v_total - v_imgs, v_total;
  end if;
  raise notice 'One Piece Characters: % items, all with portraits', v_total;
end $$;
