-- ═══════════════════════════════════════════════════════════════════════════
-- DraftFor20 · 0049 · NFL and NBA players, with free photographs
--
-- GENERATED by lib/espn.seed.test.ts (SEED=1 npx vitest run lib/espn.seed.test.ts).
-- Names and URLs are positional; editing one list without the other slides
-- every later picture onto the wrong player.
--
-- EVERY IMAGE HERE IS COMMONS-LICENSED ('free'), unlike the anime categories
-- in 0044/0046 which are fair-use promotional art. That is deliberate and it
-- is why these categories survive a freeOnly export: lib/espn.ts takes only
-- the roster from ESPN, because a roster is a fact and a photograph is not.
--
-- CURRENT ROSTERS GO STALE. Re-run the generator after a trade deadline or a
-- new season; the seed upserts by normalised name, so re-running refreshes
-- both the list and the photographs.
--
-- Re-runnable.
-- ═══════════════════════════════════════════════════════════════════════════


-- df20_seed_category UPSERTS and never removes, so re-seeding a shrunken
-- list would leave every dropped player behind.
delete from public.category_library_items i
 using public.category_library l
 where l.id = i.library_id
   and l.name_norm in (public.df20_norm_category('NFL Players'),
                       public.df20_norm_category('NBA Players'),
                       public.df20_norm_category('NFL All-Time Greats'),
                       public.df20_norm_category('NBA All-Time Greats'));

-- ── NFL Players · 37 items
select public.df20_seed_category(
  'NFL Players',
  string_to_array($it$Travis Kelce
Joe Flacco
Jayden Daniels
Aaron Rodgers
Stefon Diggs
Baker Mayfield
Patrick Mahomes
Von Miller
Josh Allen
Fernando Mendoza
Myles Garrett
Deshaun Watson
Justin Herbert
Odell Beckham Jr.
Carson Beck
Joe Burrow
Kyler Murray
Brandon Aiyuk
Kirk Cousins
Drew Allar
Sam Darnold
Christian McCaffrey
Matthew Stafford
Lamar Jackson
Jameis Winston
Jamal Adams
Tua Tagovailoa
Vita Vea
Saquon Barkley
Derrick Henry
Justin Fields
Maxx Crosby
Trevon Diggs
Jalen Hurts
Jadeveon Clowney
Dak Prescott
Davante Adams$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/f/f5/Travis_Kelce_in_the_Oval_Office_of_the_White_House_on_June_5%2C_2023_-_P20230605AS-0902_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Joe_Flacco_2025_Browns_Camp_%28cropped%29.jpg/960px-Joe_Flacco_2025_Browns_Camp_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/3/37/Jayden_Daniels_2025.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/AaronRodgersSteelers_%28cropped%29.jpg/960px-AaronRodgersSteelers_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Stefon_Diggs_SEP2021_%28cropped%29.jpg/960px-Stefon_Diggs_SEP2021_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Baker_Mayfield_%28cropped%29.jpg/960px-Baker_Mayfield_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Patrick_Mahomes_%2851615475056%29.jpg/960px-Patrick_Mahomes_%2851615475056%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Commanders_Training_Camp_-_54752497153.jpg/960px-Commanders_Training_Camp_-_54752497153.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Josh_Allen_SEPT2021_%28cropped2%29.jpg/960px-Josh_Allen_SEPT2021_%28cropped2%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/2026-0117_Fernando_Mendoza.jpeg/960px-2026-0117_Fernando_Mendoza.jpeg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Myles_Garrett_%282021%29.jpg/960px-Myles_Garrett_%282021%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Deshaun_Watson_%2853142891313%29_%28cropped%29.jpg/960px-Deshaun_Watson_%2853142891313%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Justin_Herbert_presnap_against_the_Washington_Commanders.jpg/960px-Justin_Herbert_presnap_against_the_Washington_Commanders.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Odell_Beckham_Jr._%2853103730122%29_%28cropped%29.jpg/960px-Odell_Beckham_Jr._%2853103730122%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/2026-0117_Carson_Beck.jpeg/960px-2026-0117_Carson_Beck.jpeg
https://upload.wikimedia.org/wikipedia/commons/c/c5/Joe_Burrow_-_Lordstown_interview_-_1_%28cropped%29.png
https://upload.wikimedia.org/wikipedia/commons/5/51/Kyler_Murray_in_huddle_%2850369475187%29_%28cropped%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Brandon_Aiyuk_2020_%28cropped%29.jpg/960px-Brandon_Aiyuk_2020_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Cousins_2022.jpg/960px-Cousins_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/e/e4/DrewAllar.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Seattle_Seahawks_Super_Bowl_LX_parade_-_16_%28Sam_Darnold_crop%29.jpg/960px-Seattle_Seahawks_Super_Bowl_LX_parade_-_16_%28Sam_Darnold_crop%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Christian_McCaffrey_2019.jpg/960px-Christian_McCaffrey_2019.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Stafford_6_731_%28cropped3%29.jpg/960px-Stafford_6_731_%28cropped3%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/149th_Preakness_%2853731145142%29_%28cropped%29.jpg/960px-149th_Preakness_%2853731145142%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/WFT_vs._Saints_%2851583434549%29.jpg/960px-WFT_vs._Saints_%2851583434549%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/2025_Raiders_at_Commanders_Jamal_Adams_%28cropped%29.jpg/960px-2025_Raiders_at_Commanders_Jamal_Adams_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/1/11/Tua_Tagovailoa_Miami_Dolphins_at_New_Orleans_Saints_2021_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Vita_Vea_2021_%28cropped%29.jpg/960px-Vita_Vea_2021_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/7/7c/Saquon_Barkley_112024.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Derrick_Henry_OCT2022_%28cropped%29.jpg/960px-Derrick_Henry_OCT2022_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/4/4c/2025_NYJ_Media_Day_Justin_Fields_%28cropped%29.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Maxx_Crosby_2025.jpg/960px-Maxx_Crosby_2025.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Trevon_Diggs_December_2021_%28cropped%29.jpg/960px-Trevon_Diggs_December_2021_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Jalen_Hurts_11-14-22_%28cropped%29.jpg/960px-Jalen_Hurts_11-14-22_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Jadeveon_Clowney_%2851402747630%29.jpg/960px-Jadeveon_Clowney_%2851402747630%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Dak_Prescott_by_Gage_Skidmore.jpg/960px-Dak_Prescott_by_Gage_Skidmore.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Davante_Adams_Packers_vs_WFT_OCT2021_%28cropped%29.jpg/960px-Davante_Adams_Packers_vs_WFT_OCT2021_%28cropped%29.jpg$im$, E'\n'),
  array_fill('free'::text, array[37]));

select public.df20_add_alias('NFL Players',
  array['nfl players', 'current nfl players', 'football players', 'nfl stars']);

-- ── NBA Players · 31 items
select public.df20_seed_category(
  'NBA Players',
  string_to_array($it$LeBron James
Jaylen Brown
Kawhi Leonard
Stephen Curry
Giannis Antetokounmpo
Jalen Brunson
LaMelo Ball
Victor Wembanyama
Walker Kessler
Kevin Durant
Bronny James
Paul George
Ja Morant
Klay Thompson
Karl-Anthony Towns
Kyrie Irving
DeMar DeRozan
AJ Dybantsa
James Harden
Bam Adebayo
Yaxel Lendeborg
Zaccharie Risacher
Shai Gilgeous-Alexander
Joel Embiid
Anthony Davis
Jayson Tatum
Cooper Flagg
Andre Drummond
OG Anunoby
Tyler Herro
Damian Lillard$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/960px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg
https://upload.wikimedia.org/wikipedia/commons/8/84/Celtics_at_Wizards_2024-12-015_%28cropped%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/a/a9/Kawhi_Leonard_%287440607%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/5/52/Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg/960px-Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Jalen_Brunson_2023_%28cropped%29.jpg/960px-Jalen_Brunson_2023_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/LaMelo_Ball_%28cropped%29.jpg/960px-LaMelo_Ball_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Victor_Wembanyama_San_Antonio_Spurs_2024.jpg/960px-Victor_Wembanyama_San_Antonio_Spurs_2024.jpg
https://upload.wikimedia.org/wikipedia/commons/3/34/Walker_Kessler_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg/960px-Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/e/ee/Bronny_James_Jr._%2855095342116%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/1_paul_george_2026_%28cropped%29.jpg/960px-1_paul_george_2026_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Ja_Morant_2021.jpg/960px-Ja_Morant_2021.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Klay_Thompson_%28cropped%29.jpg/960px-Klay_Thompson_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Karl-Anthony_Towns_%2851914283512%29_%28cropped%29_%28cropped%29.jpg/960px-Karl-Anthony_Towns_%2851914283512%29_%28cropped%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Kyrie_Irving_%2851830909437%29_%28cropped%29.jpg/960px-Kyrie_Irving_%2851830909437%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/DeMar_DeRozan_2022.jpg/960px-DeMar_DeRozan_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/d/da/AJ_Dybantsa_2024.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Harden_dribbling_midcourt%2C_Cavaliers_vs_Nets_on_January_17%2C_2022_%28cropped%29.jpg/960px-Harden_dribbling_midcourt%2C_Cavaliers_vs_Nets_on_January_17%2C_2022_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/7/7d/Bam_Adebayo_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/20260211_Yaxel_Lendeborg_05.jpg/960px-20260211_Yaxel_Lendeborg_05.jpg
https://upload.wikimedia.org/wikipedia/commons/9/9f/Zaccharie_Risacher_All_Star_Game_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/2023-08-09_Deutschland_gegen_Kanada_%28Basketball-L%C3%A4nderspiel%29_by_Sandro_Halank%E2%80%93109.jpg/960px-2023-08-09_Deutschland_gegen_Kanada_%28Basketball-L%C3%A4nderspiel%29_by_Sandro_Halank%E2%80%93109.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Joel_Embiid_2019.jpg/960px-Joel_Embiid_2019.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Anthony_Davis_pre-game_%28cropped%29.jpg/960px-Anthony_Davis_pre-game_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg/960px-Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Duke_at_UNC%2C_Mar_2025%2C_Flagg.jpg/960px-Duke_at_UNC%2C_Mar_2025%2C_Flagg.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/1_andre_drummond_2026.jpg/960px-1_andre_drummond_2026.jpg
https://upload.wikimedia.org/wikipedia/commons/0/03/OG_Anunoby_%2841708749222%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/7/71/Tyler_Herro_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Damian_Lillard_%282021%29_%28cropped%29.jpg/960px-Damian_Lillard_%282021%29_%28cropped%29.jpg$im$, E'\n'),
  array_fill('free'::text, array[31]));

select public.df20_add_alias('NBA Players',
  array['nba players', 'current nba players', 'basketball players', 'nba stars']);

-- ── NFL All-Time Greats · 59 items
select public.df20_seed_category(
  'NFL All-Time Greats',
  string_to_array($it$Tom Brady
Jerry Rice
Joe Montana
Peyton Manning
Walter Payton
Lawrence Taylor
Barry Sanders
Emmitt Smith
Brett Favre
Ray Lewis
John Elway
Dan Marino
Deion Sanders
Reggie White
Jim Brown
Johnny Unitas
Randy Moss
Terrell Owens
Ed Reed
Champ Bailey
Bruce Smith
Michael Strahan
Troy Aikman
Steve Young
Marshall Faulk
LaDainian Tomlinson
Adrian Peterson
Drew Brees
Ben Roethlisberger
Aaron Rodgers
Rob Gronkowski
Tony Gonzalez
Shannon Sharpe
Anthony Munoz
Dick Butkus
Joe Greene
Ronnie Lott
Night Train Lane
Gale Sayers
Earl Campbell
Eric Dickerson
Marcus Allen
Thurman Thomas
Curtis Martin
Terry Bradshaw
Roger Staubach
Bart Starr
Warren Sapp
Junior Seau
Derrick Brooks
Charles Woodson
Darrelle Revis
Von Miller
J.J. Watt
Julio Jones
Larry Fitzgerald
Calvin Johnson
Marvin Harrison
Cris Carter$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg/960px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/0/01/Super_Bowl_44_Miami_Florida_NFL_Network_South_Beach_Set_Deon_Sanders_interviews_Jerry_Rice_%284331549867%29_%28cropped%29_-_Jerry_Rice.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Joe_Montana_Super_Bowl_50_%28cropped%29.jpg/960px-Joe_Montana_Super_Bowl_50_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Peyton_Manning_%2851665689271%29.jpg/960px-Peyton_Manning_%2851665689271%29.jpg
https://upload.wikimedia.org/wikipedia/commons/6/62/1986_Jeno%27s_Pizza_-_12_-_Walter_Payton_%28Walter_Payton_crop%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/8/81/Lawrence_Taylor_in_2025_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Barry_Sanders_2019.jpg/960px-Barry_Sanders_2019.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Super_Bowl_44_Emmitt_Smith_%284344089199%29_%28cropped%29.jpg/960px-Super_Bowl_44_Emmitt_Smith_%284344089199%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Brett_Favre_Super_Bowl_50.jpg/960px-Brett_Favre_Super_Bowl_50.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Ray_Lewis_2015_%28cropped%29.jpg/960px-Ray_Lewis_2015_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/John_Elway_OCT2021_%28cropped%29.jpg/960px-John_Elway_OCT2021_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/2/24/Danmarino.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Deion_Sanders_%288216060%29_%28cropped%29.jpg/960px-Deion_Sanders_%288216060%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/3/31/Reggie_White_at_the_White_House.jpg
https://upload.wikimedia.org/wikipedia/commons/b/be/Jim_Brown_%281961%29_%28cropped%29.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/1967%20Johnny%20Unitas.jpeg?width=800
https://upload.wikimedia.org/wikipedia/commons/7/75/Randy_Moss_2016.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Terrell_Owens_2017-05-02_%2834255853692%29_%28cropped%29.jpg/960px-Terrell_Owens_2017-05-02_%2834255853692%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Ed_Reed_by_Gage_Skidmore.jpg/960px-Ed_Reed_by_Gage_Skidmore.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Champ_Bailey_2010.JPG/960px-Champ_Bailey_2010.JPG
https://upload.wikimedia.org/wikipedia/commons/f/fb/Bruce_Smith_Virginia_Tech.jpg
https://upload.wikimedia.org/wikipedia/commons/f/fa/Michael_Strahan_2022_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/1/16/Troy_aikman_2011_cropped.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Steve_Young_%286837509849%29_%28cropped%29.jpg/960px-Steve_Young_%286837509849%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Marshall_Faulk_by_Gage_Skidmore.jpg/960px-Marshall_Faulk_by_Gage_Skidmore.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/LaDainian_Tomlinson_2017_closeup.jpg/960px-LaDainian_Tomlinson_2017_closeup.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Adrian_Peterson_2026_%28cropped%29.jpg/960px-Adrian_Peterson_2026_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/MedalCeremony_1_011520_%2861_of_69%29_%2849396271982%29_%28cropped%29.jpg/960px-MedalCeremony_1_011520_%2861_of_69%29_%2849396271982%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Ben_Roethlisberger_%2851654680119%29_%28cropped%29.jpg/960px-Ben_Roethlisberger_%2851654680119%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/AaronRodgersSteelers_%28cropped%29.jpg/960px-AaronRodgersSteelers_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/231208-N-QE848-2422_%2853391476156%29_%28Rob_Gronkowski%29.jpg/960px-231208-N-QE848-2422_%2853391476156%29_%28Rob_Gronkowski%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tony_Gonzalez_Thursday_Night_Football_DEC2023_%28cropped%29.jpg/960px-Tony_Gonzalez_Thursday_Night_Football_DEC2023_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/0/08/Defense.gov_photo_essay_120106-A-AO884-354_%28Cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Anthony_Mu%C3%B1oz_2015.jpg/960px-Anthony_Mu%C3%B1oz_2015.jpg
https://upload.wikimedia.org/wikipedia/commons/f/fe/Dickbutkus.jpg
https://upload.wikimedia.org/wikipedia/commons/8/8f/Mean_Joe_Greene_1975.JPG
https://upload.wikimedia.org/wikipedia/commons/9/96/Ronnie_Lott_and_Jim_Plunkett_%28CrashCouse_Launch_PSA%29_%28cropped%29Lott.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Dick_Lane_1962.JPG/960px-Dick_Lane_1962.JPG
https://upload.wikimedia.org/wikipedia/commons/0/07/Gale_sayers_playing.jpg
https://upload.wikimedia.org/wikipedia/commons/2/2e/Earl_campbell_shaggybevo.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Eric_Dickerson.jpg/960px-Eric_Dickerson.jpg
https://upload.wikimedia.org/wikipedia/commons/5/59/Pro_Football_Hall_of_Famer_Speaks_at_Award_Ceremony_130104-A-GX635-439_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Thurman_Thomas_ESPNWeekend2010-067.jpg/960px-Thurman_Thomas_ESPNWeekend2010-067.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Curtis_Martin_at_2010_pep_rally.jpg/960px-Curtis_Martin_at_2010_pep_rally.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Terry_Bradshaw_Meet_and_Greet_ASI_Chicago_show_071521-7_%2851321819538%29.jpg/960px-Terry_Bradshaw_Meet_and_Greet_ASI_Chicago_show_071521-7_%2851321819538%29.jpg
https://upload.wikimedia.org/wikipedia/commons/5/59/President_Donald_J._Trump_Presents_Medal_of_Freedom_-_45863432812_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Bart_starr_bw.jpg/960px-Bart_starr_bw.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Warren_Sapp_by_Gage_Skidmore.jpg/960px-Warren_Sapp_by_Gage_Skidmore.jpg
https://upload.wikimedia.org/wikipedia/commons/d/d4/Junior_Seau_2.JPG
https://upload.wikimedia.org/wikipedia/commons/1/1c/Dbrooks_03_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Charles_Woodson_2014_2.JPG/960px-Charles_Woodson_2014_2.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Darrelle_Revis_ESPNWeekend2010-051.jpg/960px-Darrelle_Revis_ESPNWeekend2010-051.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Commanders_Training_Camp_-_54752497153.jpg/960px-Commanders_Training_Camp_-_54752497153.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/J.J._Watt_2018%E2%80%942.JPG/960px-J.J._Watt_2018%E2%80%942.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Julio_Jones_2019_%28cropped%29.jpg/960px-Julio_Jones_2019_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/b/bd/Larry_Fitzgerald_2017.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Calvin_Johnson_by_Gage_Skidmore.jpg/960px-Calvin_Johnson_by_Gage_Skidmore.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Marvin_Harrison_2022.jpg/960px-Marvin_Harrison_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Cris_Carter_HOF.JPG/960px-Cris_Carter_HOF.JPG$im$, E'\n'),
  array_fill('free'::text, array[59]));

select public.df20_add_alias('NFL All-Time Greats',
  array['nfl legends', 'nfl all time', 'greatest nfl players', 'football legends']);

-- ── NBA All-Time Greats · 59 items
select public.df20_seed_category(
  'NBA All-Time Greats',
  string_to_array($it$Michael Jordan
Kobe Bryant
Magic Johnson
Larry Bird
Shaquille O'Neal
Tim Duncan
Hakeem Olajuwon
Kareem Abdul-Jabbar
Wilt Chamberlain
Bill Russell
LeBron James
Stephen Curry
Kevin Durant
Dirk Nowitzki
Allen Iverson
Charles Barkley
Karl Malone
John Stockton
Scottie Pippen
Jason Kidd
Steve Nash
Dwyane Wade
Kevin Garnett
Paul Pierce
Ray Allen
Oscar Robertson
Jerry West
Elgin Baylor
Julius Erving
Moses Malone
David Robinson
Patrick Ewing
Clyde Drexler
Isiah Thomas
Dominique Wilkins
Reggie Miller
Chris Paul
Russell Westbrook
James Harden
Carmelo Anthony
Vince Carter
Tracy McGrady
Yao Ming
Manu Ginobili
Tony Parker
Pau Gasol
Chris Bosh
Rasheed Wallace
Alonzo Mourning
Gary Payton
Dennis Rodman
James Worthy
Bob Cousy
George Gervin
Nikola Jokic
Giannis Antetokounmpo
Joel Embiid
Luka Doncic
Jayson Tatum$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kobe_Bryant_Dec_2014.jpg/960px-Kobe_Bryant_Dec_2014.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Magic_Johnson_at_SXSW_2022_%2851958828669%29_%28cropped%29.jpg/960px-Magic_Johnson_at_SXSW_2022_%2851958828669%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/b/bb/Larrybird.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/TechCrunch_Disrupt_2023_-_Day_1_%28cropped%29.jpg/960px-TechCrunch_Disrupt_2023_-_Day_1_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/c/cb/Tim_Duncan_Walks_Verizon_Center%27s_Floor_%28cropped%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/8/84/Nigerian_President_Buhari_Stands_With_Secretary_Kerry%2C_U.S._Delegation_After_They_Attended_His_Inauguration_Ceremony_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Kareem_Abdul-Jabbar_May_2014.jpg/960px-Kareem_Abdul-Jabbar_May_2014.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Wilt_Chamberlain_1960_%28cropped%29_%28cropped%29.jpg/960px-Wilt_Chamberlain_1960_%28cropped%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/d/d3/Bill_russell_dribbling_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/960px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg
https://upload.wikimedia.org/wikipedia/commons/5/52/Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg/960px-Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Dirk_Nowitzki_2_%28cropped%29.jpg/960px-Dirk_Nowitzki_2_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/2/21/Allen_Iverson_headshot.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Charles_Barkley_in_2026.jpg/960px-Charles_Barkley_in_2026.jpg
https://upload.wikimedia.org/wikipedia/commons/e/e5/NBA_HOF%E2%80%99er_Karl_Malone_visits_Barksdale_%289%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/c/cf/John_Stockton_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Scottie_Pippen_5-2-22_%28cropped%29.jpg/960px-Scottie_Pippen_5-2-22_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Jason_Kidd_Nets_coach_cropped.jpg/960px-Jason_Kidd_Nets_coach_cropped.jpg
https://upload.wikimedia.org/wikipedia/commons/9/99/SteveNash2014.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Dwyane_Wade_e1.jpg/960px-Dwyane_Wade_e1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Kevin_Garnett_2008-01-13.jpg/960px-Kevin_Garnett_2008-01-13.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Paul_Pierce_2008-01-13_%28cropped%29.jpg/960px-Paul_Pierce_2008-01-13_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Ray_Allen_161208-A-HE359-046_%2831482070191%29.jpg/960px-Ray_Allen_161208-A-HE359-046_%2831482070191%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Oscar_Robertson_2024.jpg/960px-Oscar_Robertson_2024.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Jerry_West_1972.jpeg/960px-Jerry_West_1972.jpeg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Elgin_Baylor_Night_program-%28cropped%29.jpg/960px-Elgin_Baylor_Night_program-%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/0/0d/Julius_Erving_2016.jpg
https://upload.wikimedia.org/wikipedia/commons/a/a1/Moses_Malone_cropped_portrait.jpg
https://upload.wikimedia.org/wikipedia/commons/8/85/David_Robinson_2017.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Patrick_Ewing_2021_%28cropped%29.jpg/960px-Patrick_Ewing_2021_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/6/62/Clyde_Drexler_01.jpg
https://upload.wikimedia.org/wikipedia/commons/1/1e/Isiah_Thomas_2007_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Dominique_Wilkins_2022.jpg/960px-Dominique_Wilkins_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/c/c0/Reggie_Miller_crop.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Chris_Paul_%282022_All-Star_Weekend%29_%28cropped%29.jpg/960px-Chris_Paul_%282022_All-Star_Weekend%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Russell_Westbrook_%28March_21%2C_2022%29_%28cropped%29.jpg/960px-Russell_Westbrook_%28March_21%2C_2022%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Harden_dribbling_midcourt%2C_Cavaliers_vs_Nets_on_January_17%2C_2022_%28cropped%29.jpg/960px-Harden_dribbling_midcourt%2C_Cavaliers_vs_Nets_on_January_17%2C_2022_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Carmelo_Anthony_at_2025_NBA_All_Star_Weekend_%28cropped%29.jpg/960px-Carmelo_Anthony_at_2025_NBA_All_Star_Weekend_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/9/93/Vince_Carter_2013-03-25_%281%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Tracy_McGrady_1.jpg/960px-Tracy_McGrady_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Yao_Ming_in_2014_%28cropped%29.jpg/960px-Yao_Ming_in_2014_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Manu_Ginobili_Spurs-Magic011_%28cropped%29.jpg/960px-Manu_Ginobili_Spurs-Magic011_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Tony_Parker_France_20260704_%282%29.jpg/960px-Tony_Parker_France_20260704_%282%29.jpg
https://upload.wikimedia.org/wikipedia/commons/a/a1/PauCaptura.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Chris_Bosh_Open_Congress_2022.jpg/960px-Chris_Bosh_Open_Congress_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasheed_Wallace_2_cropped.jpg/960px-Rasheed_Wallace_2_cropped.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Alonzo_Mourning.jpg/960px-Alonzo_Mourning.jpg
https://upload.wikimedia.org/wikipedia/commons/1/14/Gary_Payton%2C_Miami_Heat_circa_2007_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Dennis_Rodman_02_%2834649289162%29_%28cropped%29.jpg/960px-Dennis_Rodman_02_%2834649289162%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/8/89/James_Worthy_at_UNC_Basketball_game._February_10%2C_2007.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bob_Cousy_%281%29.jpeg/960px-Bob_Cousy_%281%29.jpeg
https://upload.wikimedia.org/wikipedia/commons/d/d1/George_Gervin_ABA.jpeg
https://upload.wikimedia.org/wikipedia/commons/7/7e/Nikola_Jokic_free_throw_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg/960px-Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Joel_Embiid_2019.jpg/960px-Joel_Embiid_2019.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Luka_Doncic_%2851914951721%29_%28cropped1%29.jpg/960px-Luka_Doncic_%2851914951721%29_%28cropped1%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg/960px-Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg$im$, E'\n'),
  array_fill('free'::text, array[59]));

select public.df20_add_alias('NBA All-Time Greats',
  array['nba legends', 'nba all time', 'greatest nba players', 'basketball legends']);

-- ── assert they landed, with DISTINCT photographs ─────────────────────────
do $$
declare c text; v_total int; v_imgs int; v_distinct int;
  v_cats text[] := array['NFL Players', 'NBA Players', 'NFL All-Time Greats', 'NBA All-Time Greats'];
begin
  foreach c in array v_cats loop
    select count(*), count(i.image_url), count(distinct i.image_url)
      into v_total, v_imgs, v_distinct
      from public.category_library_items i
      join public.category_library l on l.id = i.library_id
     where l.name_norm = public.df20_norm_category(c);

    if v_total < 30 then
      raise exception 'DF20_SPORTS_TOO_SMALL: % has only % items', c, v_total;
    end if;
    if v_imgs < v_total then
      raise exception 'DF20_SPORTS_MISSING_IMAGES: % of % in % have no picture',
        v_total - v_imgs, v_total, c;
    end if;
    if v_distinct < v_total then
      raise exception 'DF20_SPORTS_DUPLICATE_IMAGES: % shares % pictures', c, v_total - v_distinct;
    end if;
    raise notice '%: % items, % distinct photographs', c, v_total, v_distinct;
  end loop;
end $$;
