-- ═══════════════════════════════════════════════════════════════════════════
-- DraftFor20 · 0050 · Fast Food and Candy, rebuilt around what people know
--
-- GENERATED by lib/brands.seed.test.ts. Names and URLs are positional.
--
-- The old lists were tail-heavy rather than wrong: Moe's Southwest Grill,
-- Potbelly, Qdoba and Quiznos in one; Zagnut, Sno-Caps, Krackel and Mr.
-- Goodbar in the other — which also managed not to contain M&M's, the most
-- viewed candy on Wikipedia. Both are now ordered by 60 days of real traffic
-- and every entry carries a logo or a wrapper.
--
-- 'nonfree': a logo is the trademark holder's, so unlike the sports
-- categories in 0049 these cannot be Commons-only.
--
-- Re-runnable. The delete matters — df20_seed_category upserts and never
-- removes, so re-seeding a shortened list would leave the old tail behind.
-- ═══════════════════════════════════════════════════════════════════════════

delete from public.category_library_items i
 using public.category_library l
 where l.id = i.library_id
   and l.name_norm in (public.df20_norm_category('Fast Food Chains'),
                       public.df20_norm_category('Candy and Sweets'));

-- ── Fast Food Chains · 42 items
select public.df20_seed_category(
  'Fast Food Chains',
  string_to_array($it$McDonald's
Starbucks
KFC
In-N-Out Burger
Chick-fil-A
Burger King
Taco Bell
Tim Hortons
Raising Cane's
Chipotle
Pizza Hut
Wendy's
Subway
Dunkin'
Dairy Queen
Domino's
Popeyes
Culver's
Five Guys
White Castle
Krispy Kreme
Shake Shack
Jersey Mike's
Little Caesars
Jack in the Box
Panda Express
Papa John's
Arby's
Whataburger
Wingstop
Panera Bread
Hardee's
Carl's Jr.
Bojangles
Sonic Drive-In
Zaxby's
Jimmy John's
Steak 'n Shake
Buffalo Wild Wings
Del Taco
Cinnabon
Auntie Anne's$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/960px-McDonald%27s_Golden_Arches.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/960px-Starbucks_Corporation_Logo_2011.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Kentucky_Fried_Chicken_%28Tallulah%2C_Louisiana%29_01.jpg/960px-Kentucky_Fried_Chicken_%28Tallulah%2C_Louisiana%29_01.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/InNOut_2021_logo.svg/960px-InNOut_2021_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Chick-fil-A_fast_food_chain_restaurant_exterior_in_Cleveland%2C_Tennessee_05.jpg/960px-Chick-fil-A_fast_food_chain_restaurant_exterior_in_Cleveland%2C_Tennessee_05.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Burger_King_2020.svg/960px-Burger_King_2020.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Taco_Bell_2023.svg/960px-Taco_Bell_2023.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Tim_Hortons%2C_Kingsville%2C_Ontario%2C_2025-06-29.jpg/960px-Tim_Hortons%2C_Kingsville%2C_Ontario%2C_2025-06-29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Raising_Cane%27s_Chicken_Fingers_logo.svg/960px-Raising_Cane%27s_Chicken_Fingers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Chipotle_Mexican_Grill_logo.svg/960px-Chipotle_Mexican_Grill_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Pizza_Hut_2025.svg/960px-Pizza_Hut_2025.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Wendy%27s_full_logo_2012.svg/960px-Wendy%27s_full_logo_2012.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/A_Subway_restaurant_in_a_strip_mall_in_Franklin%2C_North_Carolina%2C_United_States.jpg/960px-A_Subway_restaurant_in_a_strip_mall_in_Franklin%2C_North_Carolina%2C_United_States.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/A_Dunkin%27_Donuts_restaurant_in_Hiawassee%2C_Georgia%2C_United_States_01.jpg/960px-A_Dunkin%27_Donuts_restaurant_in_Hiawassee%2C_Georgia%2C_United_States_01.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Dairy_Queen_logo.svg/960px-Dairy_Queen_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Domino%27s_Pizza_Lobby_Entrance_Domino%27s_Farms_Ann_Arbor_Township_Michigan.JPG/960px-Domino%27s_Pizza_Lobby_Entrance_Domino%27s_Farms_Ann_Arbor_Township_Michigan.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Popeyes_Louisiana_Kitchen_%2851195358373%29.jpg/960px-Popeyes_Louisiana_Kitchen_%2851195358373%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Culver%27s_headquarters.jpg/960px-Culver%27s_headquarters.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Five_Guys%2C_Merritt_Island.JPG/960px-Five_Guys%2C_Merritt_Island.JPG
https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/White_Castle_logo.svg/960px-White_Castle_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Krispy_Kreme_Cannington%2C_April_2022.jpg/960px-Krispy_Kreme_Cannington%2C_April_2022.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Shake_Shack_Madison_Square.jpg/960px-Shake_Shack_Madison_Square.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Jersey_Mike%27s_logo.svg/960px-Jersey_Mike%27s_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Little_Caesars_World_Headquarters_2.jpg/960px-Little_Caesars_World_Headquarters_2.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Jack_in_the_Box_2022_logo.svg/960px-Jack_in_the_Box_2022_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Panda_Express_Storefront_%2848128044623%29.jpg/960px-Panda_Express_Storefront_%2848128044623%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Papa_Johns_New_HQ_in_Atlanta%2C_Georgia.jpg/960px-Papa_Johns_New_HQ_in_Atlanta%2C_Georgia.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Arby%27s_logo.svg/960px-Arby%27s_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Whataburger_logo.svg/960px-Whataburger_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Wingstop_logo.svg/960px-Wingstop_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Panera_Bread_The_Villages_Florida.jpg/960px-Panera_Bread_The_Villages_Florida.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Hardee%27s_fast-food_restaurant_in_Franklin%2C_North_Carolina.jpg/960px-Hardee%27s_fast-food_restaurant_in_Franklin%2C_North_Carolina.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Carls_Jr_Rancho_Cordova.jpg/960px-Carls_Jr_Rancho_Cordova.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/A_Bojangles_fast_food_restaurant_in_Hiawassee%2C_Georgia%2C_United_States_02.jpg/960px-A_Bojangles_fast_food_restaurant_in_Hiawassee%2C_Georgia%2C_United_States_02.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/SONIC_New_Logo_2020.svg/960px-SONIC_New_Logo_2020.svg.png
https://upload.wikimedia.org/wikipedia/en/d/dd/Zaxby%27s_logo.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Jimmy_John%27s_%28logo%29.svg/960px-Jimmy_John%27s_%28logo%29.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Steak_%27n_Shake_logo.svg/960px-Steak_%27n_Shake_logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Buffalo%20Wild%20Wings%20Carson%20IMG%2020180405%20110842.jpg?width=800
https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/Logo_of_Del_Taco.svg/960px-Logo_of_Del_Taco.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Cinnabon_in_King_of_Prussia_Mall.jpeg/960px-Cinnabon_in_King_of_Prussia_Mall.jpeg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Auntie_Anne%27s_in_King_of_Prussia_Mall.jpeg/960px-Auntie_Anne%27s_in_King_of_Prussia_Mall.jpeg$im$, E'\n'),
  array_fill('nonfree'::text, array[42]));

select public.df20_add_alias('Fast Food Chains',
  array['fast food', 'fast food chains', 'burger chains', 'restaurant chains']);

-- ── Candy and Sweets · 43 items
select public.df20_seed_category(
  'Candy and Sweets',
  string_to_array($it$M&M's
Toblerone
Snickers
Kit Kat
Airheads
Reese's Peanut Butter Cups
Milky Way
Skittles
Twix
Swedish Fish
Gobstopper
Gummy Bears
Nerds
Butterfinger
Tootsie Roll
Baby Ruth
Candy Corn
Jolly Rancher
Starburst
Sour Patch Kids
Pop Rocks
Mike and Ike
Twizzlers
3 Musketeers
Whoppers
Nestle Crunch
Milk Duds
Heath Bar
Hershey's Bar
Hershey's Kisses
Rolo
Almond Joy
Warheads
Mounds
Peeps
Runts
Skor
100 Grand
Hot Tamales
Laffy Taffy
Junior Mints
Ring Pop
PayDay$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Plain-M%26Ms-Pile.jpg/960px-Plain-M%26Ms-Pile.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Toblerone_3362.jpg/960px-Toblerone_3362.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Snickers-broken.png/960px-Snickers-broken.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Logo_of_the_KitKat.svg/960px-Logo_of_the_KitKat.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Airheads_candy_flavors.jpg/960px-Airheads_candy_flavors.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Reese%27s_logo.svg/960px-Reese%27s_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Milky-Way-Bars-USUK-Whole.jpg/960px-Milky-Way-Bars-USUK-Whole.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Skittles-Louisiana-2003.jpg/960px-Skittles-Louisiana-2003.jpg
https://upload.wikimedia.org/wikipedia/commons/4/43/Twix_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/6/6d/Swedish-Fish-Wrapper-Small.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Jawbreaker_plate.jpg/960px-Jawbreaker_plate.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Oursons_g%C3%A9latine_march%C3%A9_Rouffignac.jpg/960px-Oursons_g%C3%A9latine_march%C3%A9_Rouffignac.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Nerds-Candies.jpg/960px-Nerds-Candies.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Butterfinger-broken.JPG?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Tootsie-Roll-WU.jpg/960px-Tootsie-Roll-WU.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Baby-Ruth-Split.jpg/960px-Baby-Ruth-Split.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Candy-Corn.jpg/960px-Candy-Corn.jpg
https://upload.wikimedia.org/wikipedia/commons/a/ae/Jolly_rancher_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Starburst-Candies.jpg/960px-Starburst-Candies.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Sour-Patch-Kids.jpg/960px-Sour-Patch-Kids.jpg
https://upload.wikimedia.org/wikipedia/en/1/18/Pop-Rocks-Small.jpg
https://upload.wikimedia.org/wikipedia/en/8/87/New_Mike_and_Ike_Original_Fruits_packaging_launched_in_2013.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/2019-11-16_00_55_13_A_packet_of_Strawberry_Twizzlers_Twists_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg/960px-2019-11-16_00_55_13_A_packet_of_Strawberry_Twizzlers_Twists_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/3-Musketeers-Broken.jpg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Whoppers.jpg/960px-Whoppers.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Nestl%C3%A9_Crunch.jpg/960px-Nestl%C3%A9_Crunch.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/MilkDudsinawhitebowl.jpg/960px-MilkDudsinawhitebowl.jpg
https://upload.wikimedia.org/wikipedia/commons/8/89/Heath_bar_brandlogo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Hershey-bar-open.JPG/960px-Hershey-bar-open.JPG
https://upload.wikimedia.org/wikipedia/commons/c/c5/Hershey%27s_KISSES_Chocolate_Flavors_Written_on_Paper_Plume.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Rolo-Candies-US.jpg/960px-Rolo-Candies-US.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Almond-joy-broken.jpg/960px-Almond-joy-broken.jpg
https://upload.wikimedia.org/wikipedia/en/0/0a/Warheads_Candy_Logo.jpeg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Candy-Mounds-Broken.jpg/960px-Candy-Mounds-Broken.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Just_Born_Peeps_in_an_Easter_Basket.jpg/960px-Just_Born_Peeps_in_an_Easter_Basket.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Runts-2013.jpg/960px-Runts-2013.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Candy-Skor-Broken.jpg/960px-Candy-Skor-Broken.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Candy-100Grand-Broken.jpg/960px-Candy-100Grand-Broken.jpg
https://upload.wikimedia.org/wikipedia/en/f/fc/Illustration_of_Hot_Tamales_candy_packaging_in_use_since_2013.png
https://commons.wikimedia.org/wiki/Special:FilePath/Laffy-Taffy-Slab.jpg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Junior_Mints_logo.svg/960px-Junior_Mints_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/9/9a/Ring_pop_on_hand.jpg
https://upload.wikimedia.org/wikipedia/commons/8/8a/Payday_brand_logo.png$im$, E'\n'),
  array_fill('nonfree'::text, array[43]));

select public.df20_add_alias('Candy and Sweets',
  array['candy', 'candy and sweets', 'sweets', 'chocolate bars', 'candy bars']);

do $$
declare c text; v_total int; v_imgs int; v_distinct int;
  v_cats text[] := array['Fast Food Chains', 'Candy and Sweets'];
begin
  foreach c in array v_cats loop
    select count(*), count(i.image_url), count(distinct i.image_url)
      into v_total, v_imgs, v_distinct
      from public.category_library_items i
      join public.category_library l on l.id = i.library_id
     where l.name_norm = public.df20_norm_category(c);
    if v_total < 28 then raise exception 'DF20_BRANDS_TOO_SMALL: % has %', c, v_total; end if;
    if v_imgs < v_total then raise exception 'DF20_BRANDS_MISSING_IMAGES: % of % in %', v_total - v_imgs, v_total, c; end if;
    if v_distinct < v_total then raise exception 'DF20_BRANDS_DUPLICATE_IMAGES: % shares %', c, v_total - v_distinct; end if;
    raise notice '%: % items, % distinct pictures', c, v_total, v_distinct;
  end loop;
end $$;
