-- ═══════════════════════════════════════════════════════════════════════════
-- DraftFor20 · 0051 · a picture on every remaining shelf category
--
-- GENERATED by lib/library.seed.test.ts. Names and URLs are positional.
--
-- Completes what 0049 and 0050 started: the shelf had 20 categories that were
-- names alone, so every card in them drew a generated placeholder.
--
-- COMPLETE vs RANKED. US States and the three team categories keep every
-- member — the set IS the category, and cutting Wyoming for having less
-- traffic than California would be wrong. Everything else is a matter of
-- taste, so the tail is cut by real Wikipedia traffic.
--
-- 'nonfree' throughout: box art, album covers, logos and film stills are the
-- rights holder's. Same footing as the anime categories in 0044/0046, unlike
-- the Commons-only sports photographs in 0049.
--
-- Re-runnable. The delete matters — df20_seed_category upserts and never
-- removes, so re-seeding a shortened list would leave the old tail behind.
-- ═══════════════════════════════════════════════════════════════════════════

delete from public.category_library_items i
 using public.category_library l
 where l.id = i.library_id
   and l.name_norm in (public.df20_norm_category('US States'),
                       public.df20_norm_category('NFL Teams'),
                       public.df20_norm_category('NBA Teams'),
                       public.df20_norm_category('MLB Teams'),
                       public.df20_norm_category('Superheroes'),
                       public.df20_norm_category('Movie Villains'),
                       public.df20_norm_category('Disney Animated Movies'),
                       public.df20_norm_category('TV Sitcoms'),
                       public.df20_norm_category('Video Game Franchises'),
                       public.df20_norm_category('Board Games'),
                       public.df20_norm_category('Dog Breeds'),
                       public.df20_norm_category('90s Songs'),
                       public.df20_norm_category('2000s Songs'),
                       public.df20_norm_category('Breakfast Cereals'),
                       public.df20_norm_category('Soft Drinks'),
                       public.df20_norm_category('Ice Cream Flavors'),
                       public.df20_norm_category('Pizza Toppings'),
                       public.df20_norm_category('Halloween Candy'));

-- ── US States · 50 items
select public.df20_seed_category(
  'US States',
  string_to_array($it$Alabama
Alaska
Arizona
Arkansas
California
Colorado
Connecticut
Delaware
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maine
Maryland
Massachusetts
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
New Hampshire
New Jersey
New Mexico
New York
North Carolina
North Dakota
Ohio
Oklahoma
Oregon
Pennsylvania
Rhode Island
South Carolina
South Dakota
Tennessee
Texas
Utah
Vermont
Virginia
Washington
West Virginia
Wisconsin
Wyoming$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Alabama.svg/960px-Flag_of_Alabama.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/960px-Flag_of_Alaska.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arizona.svg/960px-Flag_of_Arizona.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arkansas.svg/960px-Flag_of_Arkansas.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_California.svg/960px-Flag_of_California.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Flag_of_Colorado.svg/960px-Flag_of_Colorado.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Flag_of_Connecticut.svg/960px-Flag_of_Connecticut.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Flag_of_Delaware.svg/960px-Flag_of_Delaware.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Florida.svg/960px-Flag_of_Florida.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_the_State_of_Georgia.svg/960px-Flag_of_the_State_of_Georgia.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Hawaii.svg/960px-Flag_of_Hawaii.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_Idaho.svg/960px-Flag_of_Idaho.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Illinois.svg/960px-Flag_of_Illinois.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flag_of_Indiana.svg/960px-Flag_of_Indiana.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Iowa.svg/960px-Flag_of_Iowa.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Kansas.svg/960px-Flag_of_Kansas.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flag_of_Kentucky.svg/960px-Flag_of_Kentucky.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_Louisiana.svg/960px-Flag_of_Louisiana.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_the_State_of_Maine.svg/960px-Flag_of_the_State_of_Maine.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Maryland.svg/960px-Flag_of_Maryland.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Massachusetts.svg/960px-Flag_of_Massachusetts.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_Michigan.svg/960px-Flag_of_Michigan.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Minnesota.svg/960px-Flag_of_Minnesota.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Mississippi.svg/960px-Flag_of_Mississippi.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Flag_of_Missouri.svg/960px-Flag_of_Missouri.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_Montana.svg/960px-Flag_of_Montana.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Flag_of_Nebraska.svg/960px-Flag_of_Nebraska.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Flag_of_Nevada.svg/960px-Flag_of_Nevada.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_New_Hampshire.svg/960px-Flag_of_New_Hampshire.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_New_Jersey.svg/960px-Flag_of_New_Jersey.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_New_Mexico.svg/960px-Flag_of_New_Mexico.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_New_York.svg/960px-Flag_of_New_York.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Flag_of_North_Carolina.svg/960px-Flag_of_North_Carolina.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Flag_of_North_Dakota.svg/960px-Flag_of_North_Dakota.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Ohio.svg/960px-Flag_of_Ohio.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Oklahoma.svg/960px-Flag_of_Oklahoma.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Oregon.svg/960px-Flag_of_Oregon.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Pennsylvania.svg/960px-Flag_of_Pennsylvania.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Rhode_Island.svg/960px-Flag_of_Rhode_Island.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Flag_of_South_Carolina.svg/960px-Flag_of_South_Carolina.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_South_Dakota.svg/960px-Flag_of_South_Dakota.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Tennessee.svg/960px-Flag_of_Tennessee.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Texas.svg/960px-Flag_of_Texas.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Utah.svg/960px-Flag_of_Utah.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Vermont.svg/960px-Flag_of_Vermont.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Virginia.svg/960px-Flag_of_Virginia.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Washington.svg/960px-Flag_of_Washington.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_West_Virginia.svg/960px-Flag_of_West_Virginia.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_Wisconsin.svg/960px-Flag_of_Wisconsin.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Wyoming.svg/960px-Flag_of_Wyoming.svg.png$im$, E'\n'),
  array_fill('nonfree'::text, array[50]));

-- ── NFL Teams · 32 items
select public.df20_seed_category(
  'NFL Teams',
  string_to_array($it$Arizona Cardinals
Atlanta Falcons
Baltimore Ravens
Buffalo Bills
Carolina Panthers
Chicago Bears
Cincinnati Bengals
Cleveland Browns
Dallas Cowboys
Denver Broncos
Detroit Lions
Green Bay Packers
Houston Texans
Indianapolis Colts
Jacksonville Jaguars
Kansas City Chiefs
Las Vegas Raiders
Los Angeles Chargers
Los Angeles Rams
Miami Dolphins
Minnesota Vikings
New England Patriots
New Orleans Saints
New York Giants
New York Jets
Philadelphia Eagles
Pittsburgh Steelers
San Francisco 49ers
Seattle Seahawks
Tampa Bay Buccaneers
Tennessee Titans
Washington Commanders$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Arizona_Cardinals_logo.svg/960px-Arizona_Cardinals_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Atlanta_Falcons_logo.svg/960px-Atlanta_Falcons_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Baltimore_Ravens_logo.svg/960px-Baltimore_Ravens_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Buffalo_Bills_logo.svg/960px-Buffalo_Bills_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Carolina_Panthers_logo.svg/960px-Carolina_Panthers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Chicago_Bears_logo_primary.svg/960px-Chicago_Bears_logo_primary.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Cincinnati_Bengals_logo.svg/960px-Cincinnati_Bengals_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Cleveland_Browns_logo.svg/960px-Cleveland_Browns_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Dallas_Cowboys.svg/960px-Dallas_Cowboys.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/4/44/Denver_Broncos_logo.svg/960px-Denver_Broncos_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Detroit_Lions_logo.svg/960px-Detroit_Lions_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Green_Bay_Packers_logo.svg/960px-Green_Bay_Packers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Houston_Texans_logo.svg/960px-Houston_Texans_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Indianapolis_Colts_logo.svg/960px-Indianapolis_Colts_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Jacksonville_Jaguars_logo.svg/960px-Jacksonville_Jaguars_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Kansas_City_Chiefs_logo.svg/960px-Kansas_City_Chiefs_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Las_Vegas_Raiders_logo.svg/960px-Las_Vegas_Raiders_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Los_Angeles_Chargers_logo.svg/960px-Los_Angeles_Chargers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/1/14/LA_Rams_logo.svg/960px-LA_Rams_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Miami_Dolphins_logo.svg/960px-Miami_Dolphins_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Minnesota_Vikings_logo.svg/960px-Minnesota_Vikings_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/New_England_Patriots_logo.svg/960px-New_England_Patriots_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/New_Orleans_Saints_logo.svg/960px-New_Orleans_Saints_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/New_York_Giants_logo.svg/960px-New_York_Giants_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/New_York_Jets_2024.svg/960px-New_York_Jets_2024.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/Philadelphia_Eagles_logo.svg/960px-Philadelphia_Eagles_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Pittsburgh_Steelers_logo.svg/960px-Pittsburgh_Steelers_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/San_Francisco_49ers_logo.svg/960px-San_Francisco_49ers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/Seattle_Seahawks_logo.svg/960px-Seattle_Seahawks_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Tampa_Bay_Buccaneers_logo.svg/960px-Tampa_Bay_Buccaneers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Tennessee_Titans_Logo_2026.svg/960px-Tennessee_Titans_Logo_2026.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Washington_Commanders_logo.svg/960px-Washington_Commanders_logo.svg.png$im$, E'\n'),
  array_fill('nonfree'::text, array[32]));

-- ── NBA Teams · 30 items
select public.df20_seed_category(
  'NBA Teams',
  string_to_array($it$Atlanta Hawks
Boston Celtics
Brooklyn Nets
Charlotte Hornets
Chicago Bulls
Cleveland Cavaliers
Dallas Mavericks
Denver Nuggets
Detroit Pistons
Golden State Warriors
Houston Rockets
Indiana Pacers
LA Clippers
Los Angeles Lakers
Memphis Grizzlies
Miami Heat
Milwaukee Bucks
Minnesota Timberwolves
New Orleans Pelicans
New York Knicks
Oklahoma City Thunder
Orlando Magic
Philadelphia 76ers
Phoenix Suns
Portland Trail Blazers
Sacramento Kings
San Antonio Spurs
Toronto Raptors
Utah Jazz
Washington Wizards$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/en/thumb/2/24/Atlanta_Hawks_logo.svg/960px-Atlanta_Hawks_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/960px-Boston_Celtics.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Brooklyn_Nets_primary_icon_logo_2024.svg/960px-Brooklyn_Nets_primary_icon_logo_2024.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Charlotte_Hornets_%282014%29.svg/960px-Charlotte_Hornets_%282014%29.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Chicago_Bulls_logo.svg/960px-Chicago_Bulls_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cleveland_Cavaliers_logo.svg/960px-Cleveland_Cavaliers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Dallas_Mavericks_logo.svg/960px-Dallas_Mavericks_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Denver_Nuggets.svg/960px-Denver_Nuggets.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_of_the_Detroit_Pistons.svg/960px-Logo_of_the_Detroit_Pistons.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Golden_State_Warriors_logo.svg/960px-Golden_State_Warriors_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Houston_Rockets.svg/960px-Houston_Rockets.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Indiana_Pacers.svg/960px-Indiana_Pacers.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Los_Angeles_Clippers_%282024%29.svg/960px-Los_Angeles_Clippers_%282024%29.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/960px-Los_Angeles_Lakers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/960px-Memphis_Grizzlies.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Miami_Heat_logo.svg/960px-Miami_Heat_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Milwaukee_Bucks_logo.svg/960px-Milwaukee_Bucks_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Minnesota_Timberwolves_logo.svg/960px-Minnesota_Timberwolves_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/New_Orleans_Pelicans_logo.svg/960px-New_Orleans_Pelicans_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Knicks_logo.svg/960px-New_York_Knicks_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Oklahoma_City_Thunder.svg/960px-Oklahoma_City_Thunder.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Orlando_Magic_logo.svg/960px-Orlando_Magic_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Philadelphia_76ers_logo.svg/960px-Philadelphia_76ers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Phoenix_Suns_logo.svg/960px-Phoenix_Suns_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Portland_Trail_Blazers_logo.svg/960px-Portland_Trail_Blazers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/SacramentoKings.svg/960px-SacramentoKings.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/San_Antonio_Spurs.svg/960px-San_Antonio_Spurs.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Toronto_Raptors_logo.svg/960px-Toronto_Raptors_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Utah_Jazz_logo_2025.svg/960px-Utah_Jazz_logo_2025.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Washington_Wizards_logo.svg/960px-Washington_Wizards_logo.svg.png$im$, E'\n'),
  array_fill('nonfree'::text, array[30]));

-- ── MLB Teams · 30 items
select public.df20_seed_category(
  'MLB Teams',
  string_to_array($it$Arizona Diamondbacks
Athletics
Atlanta Braves
Baltimore Orioles
Boston Red Sox
Chicago Cubs
Chicago White Sox
Cincinnati Reds
Cleveland Guardians
Colorado Rockies
Detroit Tigers
Houston Astros
Kansas City Royals
Los Angeles Angels
Los Angeles Dodgers
Miami Marlins
Milwaukee Brewers
Minnesota Twins
New York Mets
New York Yankees
Philadelphia Phillies
Pittsburgh Pirates
San Diego Padres
San Francisco Giants
Seattle Mariners
St. Louis Cardinals
Tampa Bay Rays
Texas Rangers
Toronto Blue Jays
Washington Nationals$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Arizona_Diamondbacks_logo_teal.svg/960px-Arizona_Diamondbacks_logo_teal.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Athletics_logo.svg/960px-Athletics_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Atlanta_Braves_Insignia.svg/960px-Atlanta_Braves_Insignia.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Baltimore_Orioles_cap.svg/960px-Baltimore_Orioles_cap.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/RedSoxPrimary_HangingSocks.svg/960px-RedSoxPrimary_HangingSocks.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Chicago_Cubs_logo.svg/960px-Chicago_Cubs_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Chicago_White_Sox.svg/960px-Chicago_White_Sox.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cincinnati_Reds_Logo.svg/960px-Cincinnati_Reds_Logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Guardians_winged_%22G%22.svg/960px-Guardians_winged_%22G%22.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Colorado_Rockies_full_logo.svg/960px-Colorado_Rockies_full_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Detroit_Tigers_logo.svg/960px-Detroit_Tigers_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Houston-Astros-Logo.svg/960px-Houston-Astros-Logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Kansas_City_Royals_Primary_Logo.svg/960px-Kansas_City_Royals_Primary_Logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Los_Angeles_Angels_of_Anaheim.svg/960px-Los_Angeles_Angels_of_Anaheim.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Los_Angeles_Dodgers_Logo.svg/960px-Los_Angeles_Dodgers_Logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Marlins_team_logo.svg/960px-Marlins_team_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/Milwaukee_Brewers_logo.svg/960px-Milwaukee_Brewers_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Minnesota_Twins_New_Logo.svg/960px-Minnesota_Twins_New_Logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/New_York_Mets.svg/960px-New_York_Mets.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/New_York_Yankees_Primary_Logo.svg/960px-New_York_Yankees_Primary_Logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/f/f0/Philadelphia_Phillies_%282019%29_logo.svg/960px-Philadelphia_Phillies_%282019%29_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Pittsburgh_Pirates_logo_2014.svg/960px-Pittsburgh_Pirates_logo_2014.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/SD_Logo_Brown.svg/960px-SD_Logo_Brown.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/5/58/San_Francisco_Giants_Logo.svg/960px-San_Francisco_Giants_Logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Seattle_Mariners_logo_%28low_res%29.svg/960px-Seattle_Mariners_logo_%28low_res%29.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/St._Louis_Cardinals_logo.svg/960px-St._Louis_Cardinals_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Tampa_Bay_Rays_Logo.svg/960px-Tampa_Bay_Rays_Logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Texas_Rangers_logo.svg/960px-Texas_Rangers_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Toronto_Blue_Jay_Primary_Logo.svg/960px-Toronto_Blue_Jay_Primary_Logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Washington_Nationals_logo.svg/960px-Washington_Nationals_logo.svg.png$im$, E'\n'),
  array_fill('nonfree'::text, array[30]));

-- ── Superheroes · 40 items
select public.df20_seed_category(
  'Superheroes',
  string_to_array($it$Jean Grey
Spider-Man
Punisher
Ghost Rider
Batman
Cyclops
Superman
Hulk
Green Lantern
Wolverine
Scarlet Witch
Captain America
Deadpool
Iron Man
Doctor Strange
Wonder Woman
Professor X
Thor
Mister Fantastic
Wasp
Silver Surfer
Jessica Jones
Luke Cage
Falcon
Invisible Woman
Groot
Aquaman
Human Torch
Star-Lord
Cyborg
The Flash
Rocket Raccoon
Gamora
Ant-Man
Nova
Storm
Gambit
Black Panther
Rogue
Daredevil$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/en/8/8c/Jean_Grey_%28Modern%29.webp
https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png
https://upload.wikimedia.org/wikipedia/en/a/a0/The_Punisher_One_Last_Kill_poster.jpg
https://upload.wikimedia.org/wikipedia/en/6/6e/Ghost_Rider_first_issue_cover.png
https://upload.wikimedia.org/wikipedia/en/c/c7/Batman_Infobox.jpg
https://upload.wikimedia.org/wikipedia/en/e/e9/Cyclops_%28Scott_Summers_circa_2019%29.png
https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png
https://upload.wikimedia.org/wikipedia/en/a/aa/Hulk_%28circa_2019%29.png
https://upload.wikimedia.org/wikipedia/en/8/80/Green_Lantern_Rebirth_6.jpg
https://upload.wikimedia.org/wikipedia/en/d/d3/Wolverine_%28circa_2024%29.jpg
https://upload.wikimedia.org/wikipedia/en/e/ec/Scarlet_Witch_Various_incarnations_2021.jpg
https://upload.wikimedia.org/wikipedia/en/9/9c/Captain_America_Comics-1_%28March_1941_Timely_Comics%29.jpg
https://upload.wikimedia.org/wikipedia/en/c/ca/Deadpool.png
https://upload.wikimedia.org/wikipedia/en/4/47/Iron_Man_%28circa_2018%29.png
https://upload.wikimedia.org/wikipedia/en/4/4f/Doctor_Strange_Vol_4_2_Ross_Variant_Textless.jpg
https://upload.wikimedia.org/wikipedia/en/6/6b/Wonder_Woman_750.jpg
https://upload.wikimedia.org/wikipedia/en/a/a8/Professor_X.png
https://upload.wikimedia.org/wikipedia/en/1/1a/Thor_%28Marvel_Comics%29.png
https://upload.wikimedia.org/wikipedia/en/d/d3/Mister_Fantastic.png
https://upload.wikimedia.org/wikipedia/en/c/c0/AVEN071.jpg
https://upload.wikimedia.org/wikipedia/en/3/34/Silver_Surfer.png
https://upload.wikimedia.org/wikipedia/en/6/6e/Jessica_Jones_by_Mike_Mayhew.jpg
https://upload.wikimedia.org/wikipedia/en/f/f9/Luke_Cage_by_Stuart_Immonen.png
https://upload.wikimedia.org/wikipedia/en/9/9e/Falcon_%28Samuel_Thomas_%22Sam%22_Wilson%29.png
https://upload.wikimedia.org/wikipedia/en/e/e4/Invisible_Woman.png
https://upload.wikimedia.org/wikipedia/en/3/3b/Groot.png
https://upload.wikimedia.org/wikipedia/en/9/9d/Aquaman_Rebirth_1.png
https://upload.wikimedia.org/wikipedia/en/c/c7/Human_Torch_%28Johnny_Storm%29.png
https://upload.wikimedia.org/wikipedia/en/1/15/ST1.PNG
https://upload.wikimedia.org/wikipedia/en/5/58/Cyborg_%28Victor_Stone%29.jpg
https://upload.wikimedia.org/wikipedia/en/e/ed/The_Flash_Family.jpg
https://upload.wikimedia.org/wikipedia/en/1/1b/Rocketraccoon.png
https://upload.wikimedia.org/wikipedia/en/0/08/Gamora-cover.jpg
https://upload.wikimedia.org/wikipedia/en/6/6b/Irredeemable_Ant-Man_Vol_1_5_Textless.jpg
https://upload.wikimedia.org/wikipedia/en/2/26/Nova1adigranov.jpg
https://upload.wikimedia.org/wikipedia/en/3/34/Storm_%28Ororo_Munroe%29.png
https://upload.wikimedia.org/wikipedia/en/9/94/Gambit_%28Marvel_Comics%29.png
https://upload.wikimedia.org/wikipedia/en/f/f7/Black_Panther_%28T%27Challa%29.png
https://upload.wikimedia.org/wikipedia/en/d/d3/Excalibur_2019_-18.jpeg
https://upload.wikimedia.org/wikipedia/en/1/14/Daredevil_65.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── Movie Villains · 40 items
select public.df20_seed_category(
  'Movie Villains',
  string_to_array($it$The Terminator
Hades
Hannibal Lecter
Thanos
Amon Goeth
The Joker
Anton Chigurh
Loki
Sauron
Green Goblin
Pennywise
Darth Vader
Doctor Octopus
Jason Voorhees
Emperor Palpatine
Freddy Krueger
Two-Face
Lord Voldemort
Patrick Bateman
Keyser Soze
HAL 9000
The Penguin
Norman Bates
Kylo Ren
Leatherface
Cruella de Vil
Captain Hook
Bill the Butcher
Nurse Ratched
Saruman
The Wicked Witch of the West
Immortan Joe
Regina George
Maleficent
Agent Smith
Scar
Annie Wilkes
Shere Khan
Colonel Kurtz
Hans Gruber$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/en/6/6d/The_Terminator.png
https://upload.wikimedia.org/wikipedia/en/7/76/Disney%27s_Hercules_characters.jpg
https://upload.wikimedia.org/wikipedia/en/6/6e/Hannibal_Lecter_in_Silence_of_the_Lambs.jpg
https://upload.wikimedia.org/wikipedia/en/b/b7/Thanos_%28Infobox_image%29.png
https://upload.wikimedia.org/wikipedia/commons/1/18/Amon_goeth_1946_%28cropped%29%282%29.jpg
https://upload.wikimedia.org/wikipedia/en/5/5f/Batman_Three_Jokers.jpg
https://upload.wikimedia.org/wikipedia/en/4/41/Anton_Chigurh.jpg
https://upload.wikimedia.org/wikipedia/en/e/ee/Various_incarnations_of_Loki_%282014%29.webp
https://upload.wikimedia.org/wikipedia/en/f/f8/Sauron_Tolkien_illustration.jpg
https://upload.wikimedia.org/wikipedia/en/3/35/Green_Goblin_Comic_Art_by_Miguel_Mercado.png
https://upload.wikimedia.org/wikipedia/en/5/52/Pennywise_Skarsgard_and_Curry.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Darth_Vader_at_Galaxy%E2%80%99s_Edge_%28cropped%29.jpg/960px-Darth_Vader_at_Galaxy%E2%80%99s_Edge_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/en/b/bc/Dr._Octopus_Marvel.jpg
https://upload.wikimedia.org/wikipedia/en/f/f7/Jason_Voorhees_%28Ken_Kirzinger%29.jpg
https://upload.wikimedia.org/wikipedia/en/8/8f/Emperor_RotJ.png
https://upload.wikimedia.org/wikipedia/en/e/eb/Freddy_Krueger_%28Robert_Englund%29.jpg
https://upload.wikimedia.org/wikipedia/en/0/02/TwoFaceYearOne.png
https://upload.wikimedia.org/wikipedia/en/2/2a/Voldemort_book_and_film.jpg
https://upload.wikimedia.org/wikipedia/en/5/52/American-psycho-patrick-bateman.jpg
https://upload.wikimedia.org/wikipedia/en/5/5c/Keyser_S%C3%B6ze_-_photo.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/HAL9000.svg?width=800
https://upload.wikimedia.org/wikipedia/en/f/f2/Penguin_%28Oswald_Cobblepot%29.png
https://upload.wikimedia.org/wikipedia/commons/f/f4/Anthony_Perkins_Psycho_Publicity_Photo_%28cropped_3%29.jpg
https://upload.wikimedia.org/wikipedia/en/3/34/Kylo_Ren.png
https://upload.wikimedia.org/wikipedia/en/9/94/Leatherface%2C_The_Texas_Chain_Saw_Massacre%2C_1974%2C_Colorized.jpg
https://upload.wikimedia.org/wikipedia/en/6/64/Cruella_de_Vil.png
https://upload.wikimedia.org/wikipedia/commons/0/0a/Captain_Hook.PNG
https://upload.wikimedia.org/wikipedia/commons/2/24/Bill_Poole.jpg
https://upload.wikimedia.org/wikipedia/en/e/ed/Nurse_Ratched.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Escudo_Isengard.svg/960px-Escudo_Isengard.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Wicked%20Witch%20of%20the%20West.png?width=800
https://upload.wikimedia.org/wikipedia/en/c/c5/ImmortanJoeMadMax.jpeg
https://upload.wikimedia.org/wikipedia/en/0/0f/Regina_George.jpg
https://upload.wikimedia.org/wikipedia/en/7/7e/Malefica.jpg
https://upload.wikimedia.org/wikipedia/en/1/1f/Agent_Smith_%28The_Matrix_series_character%29.jpg
https://upload.wikimedia.org/wikipedia/en/4/4d/Scar_lion_king.png
https://upload.wikimedia.org/wikipedia/en/3/3e/KathyWilkins1212.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Becque_-_Livre_de_la_jungle%2C_p27.jpeg/960px-Becque_-_Livre_de_la_jungle%2C_p27.jpeg
https://upload.wikimedia.org/wikipedia/en/c/c0/Colonel_Kurtz.jpg
https://upload.wikimedia.org/wikipedia/en/8/8b/HansGruber.jpeg$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── Disney Animated Movies · 40 items
select public.df20_seed_category(
  'Disney Animated Movies',
  string_to_array($it$Pocahontas
Robin Hood
Dinosaur
The Lion King
Tangled
Lilo and Stitch
Atlantis: The Lost Empire
Alice in Wonderland
Encanto
The Princess and the Frog
Zootopia
Hercules
Winnie the Pooh
Frozen II
The Emperor's New Groove
Treasure Planet
Cinderella
Meet the Robinsons
Wreck-It Ralph
The Fox and the Hound
Raya and the Last Dragon
One Hundred and One Dalmatians
The Hunchback of Notre Dame
The Aristocats
Oliver and Company
Bambi
The Little Mermaid
Brother Bear
Ralph Breaks the Internet
Pinocchio
Tarzan
Aladdin
Snow White and the Seven Dwarfs
Lady and the Tramp
Dumbo
The Jungle Book
The Rescuers
Mulan
The Great Mouse Detective
Beauty and the Beast$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/en/5/57/Pocahontasposter.jpg
https://upload.wikimedia.org/wikipedia/en/9/91/Robinhood_1973_poster.png
https://upload.wikimedia.org/wikipedia/en/b/bc/Dinosaurmovieposter.jpg
https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg
https://upload.wikimedia.org/wikipedia/en/a/a8/Tangled_poster.jpg
https://upload.wikimedia.org/wikipedia/en/c/c6/LiloandStitchmovieposter.jpg
https://upload.wikimedia.org/wikipedia/en/d/de/Atlantis_The_Lost_Empire_poster.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Alice_in_Wonderland_Poster.png/960px-Alice_in_Wonderland_Poster.png
https://upload.wikimedia.org/wikipedia/en/8/83/Encanto_poster.jpg
https://upload.wikimedia.org/wikipedia/en/8/81/The_Princess_and_the_Frog_poster.jpg
https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg
https://upload.wikimedia.org/wikipedia/en/6/65/Hercules_%281997_film%29_poster.jpg
https://upload.wikimedia.org/wikipedia/en/1/10/Winniethepooh.png
https://upload.wikimedia.org/wikipedia/en/8/89/Frozen_II_%282019_animated_film%29.jpg
https://upload.wikimedia.org/wikipedia/en/6/69/Grooveposter.jpg
https://upload.wikimedia.org/wikipedia/en/7/7e/Treasure_Planet_poster.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/1950_is_the_Cinderella_year.jpg/960px-1950_is_the_Cinderella_year.jpg
https://upload.wikimedia.org/wikipedia/en/d/dc/Meet_the_robinsons.jpg
https://upload.wikimedia.org/wikipedia/en/1/15/Wreckitralphposter.jpeg
https://upload.wikimedia.org/wikipedia/en/7/70/The_Fox_and_the_Hound.jpg
https://upload.wikimedia.org/wikipedia/en/e/ea/Raya_and_the_Last_Dragon.png
https://upload.wikimedia.org/wikipedia/en/c/cd/One_Hundred_and_One_Dalmatians_movie_poster.jpg
https://upload.wikimedia.org/wikipedia/en/2/26/The_Hunchback_of_Notre_Dame_1996_poster.jpg
https://upload.wikimedia.org/wikipedia/en/8/8d/Aristoposter.jpg
https://upload.wikimedia.org/wikipedia/en/f/fd/Oliver_poster.jpg
https://upload.wikimedia.org/wikipedia/en/8/88/Walt_Disney%27s_Bambi_poster.jpg
https://upload.wikimedia.org/wikipedia/en/c/c0/The_Little_Mermaid_%28Official_1989_Film_Poster%29.png
https://upload.wikimedia.org/wikipedia/en/8/86/Brother_Bear_Poster.png
https://upload.wikimedia.org/wikipedia/en/0/0b/Ralph_Breaks_the_Internet_%282018_film_poster%29.png
https://upload.wikimedia.org/wikipedia/commons/6/65/Pinocchio.jpg
https://upload.wikimedia.org/wikipedia/en/4/4f/Tarzan_%281999_film%29_-_theatrical_poster.jpg
https://upload.wikimedia.org/wikipedia/en/b/be/Aladdin_Disney_pose.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Snow_White_and_the_Seven_Dwarfs_%28Style_B%29_poster.jpg/960px-Snow_White_and_the_Seven_Dwarfs_%28Style_B%29_poster.jpg
https://upload.wikimedia.org/wikipedia/en/3/39/Lady-and-tramp-1955-poster.jpg
https://upload.wikimedia.org/wikipedia/en/a/a7/Dumbo-1941-poster.jpg
https://upload.wikimedia.org/wikipedia/en/1/1d/Thejunglebook_movieposter.jpg
https://upload.wikimedia.org/wikipedia/en/a/ac/Rescuersposter.jpg
https://upload.wikimedia.org/wikipedia/en/a/a3/Movie_poster_mulan.JPG
https://upload.wikimedia.org/wikipedia/en/a/a4/Mousedetectposter.jpg
https://upload.wikimedia.org/wikipedia/en/5/5e/Beauty_and_the_Beast_%281991_film%29_poster.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── TV Sitcoms · 40 items
select public.df20_seed_category(
  'TV Sitcoms',
  string_to_array($it$Ted Lasso
The Big Bang Theory
The Simpsons
It's Always Sunny in Philadelphia
Friends
Modern Family
Malcolm in the Middle
Family Guy
The Golden Girls
Curb Your Enthusiasm
How I Met Your Mother
Seinfeld
South Park
Parks and Recreation
Schitt's Creek
Arrested Development
Abbott Elementary
Brooklyn Nine-Nine
30 Rock
Cheers
Frasier
The Good Place
Everybody Loves Raymond
Full House
Happy Days
Married with Children
The Fresh Prince of Bel-Air
Roseanne
Veep
Will and Grace
Boy Meets World
Saved by the Bell
Three's Company
All in the Family
Family Matters
I Love Lucy
Sanford and Son
Night Court
Good Times
Spin City$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/en/7/73/Tedlassotitlecard.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/TBBT_logo.svg/960px-TBBT_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/The_Simpsons_yellow_logo.svg/960px-The_Simpsons_yellow_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/IASIPTC.svg/960px-IASIPTC.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Friends%20logo.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Modern%20Family%20Title.svg?width=800
https://upload.wikimedia.org/wikipedia/en/a/ae/MitM_credits_logo.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Family_Guy_Logo.svg/960px-Family_Guy_Logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Golden%20Girls%20title.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Curbyourenthusiasm.png?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/HowIMetYourMother.svg/960px-HowIMetYourMother.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Seinfeld_logo.svg/960px-Seinfeld_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/5/59/South_Park.png
https://commons.wikimedia.org/wiki/Special:FilePath/Parks%20and%20Recreation%20(7269061104).jpg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Schitt%27s_Creek_logo.svg/960px-Schitt%27s_Creek_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Arrested_Development.svg/960px-Arrested_Development.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Abbott_Elementary_logo.svg/960px-Abbott_Elementary_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/f/fc/Brooklyn_Nine-Nine_Season_7.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/30Rock%20logo.svg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cheers.svg/960px-Cheers.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Frasier_title_logo.svg/960px-Frasier_title_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/The_Good_Place_title_card.svg/960px-The_Good_Place_title_card.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Everybody_Loves_Raymond_logo.svg/960px-Everybody_Loves_Raymond_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Full_House_-_original_title_screen_logo.svg/960px-Full_House_-_original_title_screen_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Happy_Days_%28Miller-Boyett%29_original_logo.svg/960px-Happy_Days_%28Miller-Boyett%29_original_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Married_%E2%80%A6_With_Children_%28Sony_Pictures_Television_series_logo%29.svg/960px-Married_%E2%80%A6_With_Children_%28Sony_Pictures_Television_series_logo%29.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Fresh_Prince_Bel_Aire_logo.svg/960px-Fresh_Prince_Bel_Aire_logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Roseanne%20Logo.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Veep%20Logo.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Will%20%26%20Grace%20Logo.png?width=800
https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Boy_Meets_World_-_ABC_Signature_logo.svg/960px-Boy_Meets_World_-_ABC_Signature_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Saved_by_the_Bell_%28original_series%29_logo_%282%29.svg/960px-Saved_by_the_Bell_%28original_series%29_logo_%282%29.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Three%27s_Company_yellow_logo.svg/960px-Three%27s_Company_yellow_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/All_in_the_Family_%28official_television_logo%29.svg/960px-All_in_the_Family_%28official_television_logo%29.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Family_Matters_%28Miller-Boyett_Productions%29_text_logo.svg/960px-Family_Matters_%28Miller-Boyett_Productions%29_text_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/I_Love_Lucy_title.svg/960px-I_Love_Lucy_title.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sanford_and_son_logo.png/960px-Sanford_and_son_logo.png
https://upload.wikimedia.org/wikipedia/en/b/b8/Night_Court_title_screen.jpg
https://upload.wikimedia.org/wikipedia/en/5/51/Good_Times_Title_Screen.jpg
https://upload.wikimedia.org/wikipedia/en/c/c7/Spin_City_-_title.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── Video Game Franchises · 40 items
select public.df20_seed_category(
  'Video Game Franchises',
  string_to_array($it$FIFA
Call of Duty
Assassin's Creed
Minecraft
Grand Theft Auto
Resident Evil
Pokemon
The Legend of Zelda
Mortal Kombat
Elden Ring
Sonic the Hedgehog
Final Fantasy
Metal Gear
Need for Speed
Tomb Raider
Super Mario
Fire Emblem
Street Fighter
Uncharted
BioShock
Dark Souls
The Last of Us
Far Cry
Tekken
Monster Hunter
Counter-Strike
The Sims
Metroid
Splatoon
Animal Crossing
Donkey Kong
Forza
Madden NFL
Civilization
StarCraft
Left 4 Dead
SimCity
Overwatch
Fallout
Halo$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Easports_fifa_logo.svg/960px-Easports_fifa_logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Call%20of%20Duty%20logo%202023.svg?width=800
https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Assassin%27s_Creed_Logo.svg/960px-Assassin%27s_Creed_Logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Minecraft%20Alex%20and%20fauna.png?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Grand_Theft_Auto_logo_series.svg/960px-Grand_Theft_Auto_logo_series.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/The%20Resident%20Evil%20logo.svg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/960px-International_Pok%C3%A9mon_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Zelda_2017.svg/960px-Zelda_2017.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/b/b1/Mortal_Kombat_Logo.svg/960px-Mortal_Kombat_Logo.svg.png
https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Sonic_The_Hedgehog.svg/960px-Sonic_The_Hedgehog.svg.png
https://upload.wikimedia.org/wikipedia/en/d/d8/FF1_USA_boxart.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Metal%20Gear%20franchise%20logo.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Need%20for%20Speed%20logo%20(2022-present).svg?width=800
https://upload.wikimedia.org/wikipedia/en/9/9b/Tomb_Raider_Logo_2022.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/960px-Mario_Series_Logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Fire%20Emblem%20logo.svg?width=800
https://upload.wikimedia.org/wikipedia/en/e/e9/Street_Fighter_Logo.png
https://commons.wikimedia.org/wiki/Special:FilePath/Uncharted%20logo.png?width=800
https://upload.wikimedia.org/wikipedia/en/6/6d/BioShock_cover.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Dark%20Souls%20logo%20black.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/The%20Last%20of%20Us%20logo.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Far%20Cry%20logo.svg?width=800
https://commons.wikimedia.org/wiki/Special:FilePath/Tekken%20series%20logo.svg?width=800
https://upload.wikimedia.org/wikipedia/en/7/71/Monster_Hunter_logo.png
https://commons.wikimedia.org/wiki/Special:FilePath/Counter-Strike.svg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/The_Sims_series_logo.svg/960px-The_Sims_series_logo.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Metroid%20Logo%202017.svg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Splatoon_monochrome_logo.svg/960px-Splatoon_monochrome_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/9/9e/Animal_Crossing_Logo.png
https://upload.wikimedia.org/wikipedia/en/2/23/Donkey_Kong_94_box_art.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Forza_logo_2020.svg/960px-Forza_logo_2020.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Madden%20NFL%20tournament%20(3786421444).jpg?width=800
https://upload.wikimedia.org/wikipedia/en/e/ec/Civilizationboxart.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/StarCraft%20Logo.png?width=800
https://upload.wikimedia.org/wikipedia/en/5/5b/Left4Dead_Windows_cover.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Logo%20of%20SimCity.png?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Overwatch.svg/960px-Overwatch.svg.png
https://upload.wikimedia.org/wikipedia/en/a/af/Fallout.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Halo%20(series)%20logo.svg?width=800$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── Board Games · 36 items
select public.df20_seed_category(
  'Board Games',
  string_to_array($it$Chess
Backgammon
Battleship
Carcassonne
Yahtzee
Catan
Taboo
Checkers
Dominion
Scrabble
Mancala
Scythe
Jenga
Pandemic
Chutes and Ladders
Cranium
Monopoly
The Game of Life
Connect Four
Trivial Pursuit
Munchkin
Exploding Kittens
Stratego
Terraforming Mars
Candy Land
Risk
Axis and Allies
Skip-Bo
Guess Who?
Go
Phase 10
Boggle
Pictionary
Codenames
Gloomhaven
Betrayal at House on the Hill$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/6/6f/ChessSet.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Backgammon_lg.png/960px-Backgammon_lg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Hra_n%C3%A1mo%C5%99n%C3%AD_bitva_%281%29.jpg/960px-Hra_n%C3%A1mo%C5%99n%C3%AD_bitva_%281%29.jpg
https://upload.wikimedia.org/wikipedia/en/5/5e/Carcassonne-game.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Original_Yahtzee_game_set_-_1980s_UK_release.jpg/960px-Original_Yahtzee_game_set_-_1980s_UK_release.jpg
https://upload.wikimedia.org/wikipedia/en/a/a3/Catan-2015-boxart.jpg
https://upload.wikimedia.org/wikipedia/commons/1/19/Taboo_02.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/CheckersStandard.jpg/960px-CheckersStandard.jpg
https://upload.wikimedia.org/wikipedia/en/b/b5/Dominion_game.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Scrabble_game_in_progress.jpg/960px-Scrabble_game_in_progress.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Yao_People_Playing_%22Bawo%22.jpg/960px-Yao_People_Playing_%22Bawo%22.jpg
https://upload.wikimedia.org/wikipedia/en/1/1a/Scythe_boxart.png
https://upload.wikimedia.org/wikipedia/commons/e/e7/Jenga_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/3/36/Pandemic_game.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Snakes_and_Ladders.jpg/960px-Snakes_and_Ladders.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Cranium_game.jpg/960px-Cranium_game.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Monopoly_board_on_white_bg.jpg/960px-Monopoly_board_on_white_bg.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/The_Game_of_Life_%E4%BA%BA%E7%94%9F%E3%82%B2%E3%83%BC%E3%83%A0_DSCF2280.jpg/960px-The_Game_of_Life_%E4%BA%BA%E7%94%9F%E3%82%B2%E3%83%BC%E3%83%A0_DSCF2280.jpg
https://upload.wikimedia.org/wikipedia/commons/8/84/Connect-four.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Trivial_pursuit_classic_edition_cover.jpg/960px-Trivial_pursuit_classic_edition_cover.jpg
https://upload.wikimedia.org/wikipedia/en/e/ee/Munchkin_game_cover.jpg
https://upload.wikimedia.org/wikipedia/en/a/a6/Exploding_Kittens.png
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Essen_2008_50016.jpg/960px-Essen_2008_50016.jpg
https://upload.wikimedia.org/wikipedia/en/f/f0/Terraforming_Mars_board_game_box_cover.jpg
https://upload.wikimedia.org/wikipedia/en/4/46/Candy_land_mb_cover_1949.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Amsterdam_-_Risk_players_-_1136_%28cropped%29.jpg/960px-Amsterdam_-_Risk_players_-_1136_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/6/61/Axis_n_allies_europe_%28356614157%29.jpg
https://upload.wikimedia.org/wikipedia/en/8/8d/Skip-Bo_cover.JPG
https://upload.wikimedia.org/wikipedia/commons/8/8d/Guess_who_game_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/FloorGoban.JPG/960px-FloorGoban.JPG
https://upload.wikimedia.org/wikipedia/commons/e/e3/Phase_10.jpg
https://upload.wikimedia.org/wikipedia/commons/f/f4/Boggle.jpg
https://upload.wikimedia.org/wikipedia/commons/5/5d/Pictionary_Party.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Codenames_board_game.jpg/960px-Codenames_board_game.jpg
https://upload.wikimedia.org/wikipedia/en/e/ee/Gloomhaven_Cover_Art.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Play%20310%201688424591864.jpg?width=800$im$, E'\n'),
  array_fill('nonfree'::text, array[36]));

-- ── Dog Breeds · 40 items
select public.df20_seed_category(
  'Dog Breeds',
  string_to_array($it$Dachshund
Newfoundland
Golden Retriever
German Shepherd
Rottweiler
Labrador Retriever
Shih Tzu
Shiba Inu
Australian Cattle Dog
Bernese Mountain Dog
Border Collie
Beagle
Poodle
Great Dane
Jack Russell Terrier
Australian Shepherd
Doberman Pinscher
Vizsla
Cavalier King Charles Spaniel
French Bulldog
Pug
Cocker Spaniel
Havanese
Bulldog
Corgi
Schnauzer
Alaskan Malamute
Siberian Husky
Bichon Frise
Greyhound
Yorkshire Terrier
Basset Hound
Bloodhound
Weimaraner
Whippet
Boston Terrier
Mastiff
West Highland White Terrier
Airedale Terrier
Scottish Terrier$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/%EB%8B%A5%EC%8A%A4%ED%9B%88%ED%8A%B8%28%EB%8B%A8%EB%AA%A8%EC%A2%85%29_%28Dachshund_%28Short%29%29.jpg/960px-%EB%8B%A5%EC%8A%A4%ED%9B%88%ED%8A%B8%28%EB%8B%A8%EB%AA%A8%EC%A2%85%29_%28Dachshund_%28Short%29%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Newfoundland_dog_Smoky.jpg/960px-Newfoundland_dog_Smoky.jpg
https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg
https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Rottweiler_standing_facing_left.jpg/960px-Rottweiler_standing_facing_left.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Labrador_on_Quantock_%282175262184%29.jpg/960px-Labrador_on_Quantock_%282175262184%29.jpg
https://upload.wikimedia.org/wikipedia/commons/d/df/Shihtzu_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Taka_Shiba.jpg/960px-Taka_Shiba.jpg
https://upload.wikimedia.org/wikipedia/commons/c/cc/ACD-blue-spud.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/3-BerneseMountainDogInGrass.jpg/960px-3-BerneseMountainDogInGrass.jpg
https://upload.wikimedia.org/wikipedia/commons/e/e4/Border_Collie_600.jpg
https://upload.wikimedia.org/wikipedia/commons/5/55/Beagle_600.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Full_attention_%288067543690%29.jpg/960px-Full_attention_%288067543690%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Dog_niemiecki_%C5%BC%C3%B3%C5%82ty_LM980.jpg/960px-Dog_niemiecki_%C5%BC%C3%B3%C5%82ty_LM980.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Jack_Russell_Terrier_1.jpg/960px-Jack_Russell_Terrier_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Australian_Shepherd_red_bi.JPG/960px-Australian_Shepherd_red_bi.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Dobermann_handling.jpg/960px-Dobermann_handling.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Wy%C5%BCe%C5%82_w%C4%99gierski_g%C5%82adkow%C5%82osy_500.jpg/960px-Wy%C5%BCe%C5%82_w%C4%99gierski_g%C5%82adkow%C5%82osy_500.jpg
https://upload.wikimedia.org/wikipedia/commons/5/5f/CarterBIS.Tiki.13.6.09.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/2008-07-28_Dog_at_Frolick_Field.jpg/960px-2008-07-28_Dog_at_Frolick_Field.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Mops-duke-mopszucht-vom-maegdebrunnen.jpg/960px-Mops-duke-mopszucht-vom-maegdebrunnen.jpg
https://upload.wikimedia.org/wikipedia/commons/2/28/Gessa_d%27Aran_Copo_de_Nieve-_arancio_roano-_prop.Kalesa.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/A_Havanese_judging.jpg/960px-A_Havanese_judging.jpg
https://upload.wikimedia.org/wikipedia/commons/a/a3/Whitebulldog.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Pembroke_and_Cardigan_Welsh_Corgi.jpg/960px-Pembroke_and_Cardigan_Welsh_Corgi.jpg
https://upload.wikimedia.org/wikipedia/commons/3/3c/Schnauzer_Size_Montage.png
https://upload.wikimedia.org/wikipedia/commons/9/9f/Alaskan_Malamute.jpg
https://upload.wikimedia.org/wikipedia/commons/8/8b/Husky_L.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bichon_Fris%C3%A9_-_studdogbichon.jpg/960px-Bichon_Fris%C3%A9_-_studdogbichon.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/GraceTheGreyhound.jpg/960px-GraceTheGreyhound.jpg
https://upload.wikimedia.org/wikipedia/commons/4/41/%282_version%29_Grupp_3%2C_YORKSHIRETERRIER%2C_NO_UCH_SE_UCH_Oxzar_Amazing_Bel%E2%80%99s_Toffy_%2824310212305%29.jpg
https://upload.wikimedia.org/wikipedia/commons/c/cf/BassetHound_profil.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Bloodhound_Erland22.jpg/960px-Bloodhound_Erland22.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Weimaraner_Freika-2.jpg/960px-Weimaraner_Freika-2.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Whippet_2018_6.jpg/960px-Whippet_2018_6.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Boston-terrier-carlos-de.JPG/960px-Boston-terrier-carlos-de.JPG
https://upload.wikimedia.org/wikipedia/commons/e/e1/Spanish_Mastiff.JPG
https://upload.wikimedia.org/wikipedia/commons/2/2c/West_Highland_White_Terrier_Krakow.jpg
https://upload.wikimedia.org/wikipedia/commons/5/52/Airedale_Terrier.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Scottish_Terrier_Photo_of_Face.jpg/960px-Scottish_Terrier_Photo_of_Face.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── 90s Songs · 40 items
select public.df20_seed_category(
  '90s Songs',
  string_to_array($it$I Will Always Love You
Wonderwall
Zombie
Lithium
Smells Like Teen Spirit
...Baby One More Time
Gangsta's Paradise
Don't Look Back in Anger
Groove Is in the Heart
Black Hole Sun
Wannabe
Killing in the Name
Losing My Religion
California Love
Under the Bridge
Waterfalls
Song 2
Semi-Charmed Life
No Scrubs
Common People
Jump Around
Plush
Heart-Shaped Box
One Headlight
Man in the Box
Sabotage
Everybody Hurts
1979
Bullet with Butterfly Wings
No Rain
Would?
Bulls on Parade
Big Poppa
Interstate Love Song
When I Come Around
Creep
Alive
Vogue
Believe
Live Forever$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/4/48/I_will_always_love_you_by_Dolly_Parton_1974_US_single.png
https://upload.wikimedia.org/wikipedia/en/1/17/Wonderwall_cover.jpg
https://upload.wikimedia.org/wikipedia/en/1/16/The_Cranberries_-_Zombie.jpg
https://upload.wikimedia.org/wikipedia/en/6/6c/Nirvana-lithium-geffen-2-s.jpg
https://upload.wikimedia.org/wikipedia/en/3/3c/Smells_Like_Teen_Spirit.jpg
https://upload.wikimedia.org/wikipedia/en/e/ec/...Baby_One_More_Time_Single.png
https://coverartarchive.org/release-group/02994ff3-e782-30da-9d57-1f35d67a2c67/front-500
https://upload.wikimedia.org/wikipedia/en/7/7e/Dontlookbackinanger.jpg
https://coverartarchive.org/release-group/bcbb7be1-0bd8-3b9a-9d40-eeab95d6e29d/front-500
https://upload.wikimedia.org/wikipedia/en/6/6b/Black_Hole_Sun.jpg
https://upload.wikimedia.org/wikipedia/en/6/63/Wannabe_Single.png
https://coverartarchive.org/release-group/be4f96a6-22ab-3e52-9db0-176925024736/front-500
https://coverartarchive.org/release-group/385d07e2-f888-3fce-b115-b0feadcb2920/front-500
https://upload.wikimedia.org/wikipedia/commons/d/db/California_Love_%281995%29%2C_by_Tupac_Shakur.png
https://coverartarchive.org/release-group/fb15c8c8-c424-3a30-9a92-c3f14a923474/front-500
https://coverartarchive.org/release-group/4f106000-ef8a-3d24-9952-6f3d3751d923/front-500
https://coverartarchive.org/release-group/d012ca8c-f29e-3bf1-a32e-1ce3f7afeba0/front-500
https://coverartarchive.org/release-group/9b938fdc-af7d-35b3-8b68-519e2b7e6470/front-500
https://upload.wikimedia.org/wikipedia/en/a/ae/Tlc-noscubs2.jpg
https://coverartarchive.org/release-group/81b56e79-e6ab-30ea-a627-7b0e06b167b6/front-500
https://upload.wikimedia.org/wikipedia/en/7/7b/Jump_Around_HOP.jpg
https://coverartarchive.org/release-group/a12e394d-7739-382a-ab68-d9f6bdb4fd60/front-500
https://coverartarchive.org/release-group/57447544-1ec9-3af5-83fe-f90a6902e078/front-500
https://upload.wikimedia.org/wikipedia/en/9/93/One_Headlight.jpg
https://upload.wikimedia.org/wikipedia/en/4/49/Man_in_the_Box_by_Alice_in_Chains_US_commercial_cassette.png
https://upload.wikimedia.org/wikipedia/en/e/e5/Sabotage_single.jpg
https://upload.wikimedia.org/wikipedia/en/1/18/R.E.M._-_Everybody_Hurts.jpg
https://coverartarchive.org/release-group/62713bbc-69c4-38b1-a35d-ea24150523fe/front-500
https://coverartarchive.org/release-group/e5a7a682-a3fa-465b-ba32-f9a0e210e455/front-500
https://upload.wikimedia.org/wikipedia/en/0/03/No_Rain_by_Blind_Melon.jpg
https://coverartarchive.org/release-group/bb5379c9-507e-3915-ba85-9ff301f6b3f1/front-500
https://coverartarchive.org/release-group/67822930-22cd-37e5-9e85-d47eaed0085a/front-500
https://upload.wikimedia.org/wikipedia/en/d/d2/BigPoppa.jpg
https://coverartarchive.org/release-group/45aa343e-70f8-3ae3-be66-983c8fc40caa/front-500
https://coverartarchive.org/release-group/bd17cc20-84b7-3c18-aa3a-4979dac23e44/front-500
https://coverartarchive.org/release-group/471b4ff5-004f-4a7b-b0ba-a0837c41da14/front-500
https://coverartarchive.org/release-group/5e09f94b-ccc5-3b22-bdb9-021e9476ab11/front-500
https://upload.wikimedia.org/wikipedia/en/8/81/Madonna%2C_Vogue_cover.png
https://upload.wikimedia.org/wikipedia/en/d/d9/Cher_-_Believe_%28single%29.png
https://coverartarchive.org/release-group/ebfe0585-0a8f-3eee-be0e-cb990dc97811/front-500$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── 2000s Songs · 40 items
select public.df20_seed_category(
  '2000s Songs',
  string_to_array($it$Mr. Brightside
American Idiot
Seven Nation Army
Hips Don't Lie
Bring Me to Life
Promiscuous
Viva la Vida
Party in the U.S.A.
A Thousand Miles
Clocks
Lose Yourself
Yellow
Maps
Hey Ya!
Chop Suey!
Kryptonite
Feel Good Inc.
Umbrella
In Da Club
I Gotta Feeling
Sk8er Boi
Chasing Cars
Paper Planes
Bye Bye Bye
In the End
Crazy in Love
Since U Been Gone
Drops of Jupiter
All the Small Things
How You Remind Me
SexyBack
Get the Party Started
Hot in Herre
Toxic
Somebody Told Me
Beautiful Day
Use Somebody
Boom Boom Pow
Independent Women
Dilemma$it$, E'\n'),
  string_to_array($im$https://coverartarchive.org/release-group/5d59bcbf-94cc-3bd6-a65d-89200d55ba07/front-500
https://coverartarchive.org/release-group/de9bf827-a9b0-348b-a7c9-556c03c3fb07/front-500
https://coverartarchive.org/release-group/a0d5a09b-8b6b-32d0-a025-105e68146fa1/front-500
https://coverartarchive.org/release-group/42670af5-a4a3-3529-ac31-6aefe8c4e765/front-500
https://coverartarchive.org/release-group/a35bcaf6-8e4a-3087-9b3b-d1295a2d4dbb/front-500
https://coverartarchive.org/release-group/04555eea-c758-35d8-be41-58d7bba9cebf/front-500
https://upload.wikimedia.org/wikipedia/en/8/84/Coldplay_-_Viva_la_Vida.jpg
https://upload.wikimedia.org/wikipedia/en/5/53/Party_in_the_USA.jpg
https://coverartarchive.org/release-group/18ef86b9-8471-3735-885c-8afa94957d0b/front-500
https://coverartarchive.org/release-group/6cbada78-bb2d-3f91-914c-caa11f8879cb/front-500
https://coverartarchive.org/release-group/88df7110-f219-3821-83b8-56443eaa34c3/front-500
https://coverartarchive.org/release-group/8049edc0-0bf7-319c-a9b3-ae9922fc0160/front-500
https://upload.wikimedia.org/wikipedia/en/d/da/Maps_%28song%29_cover.jpg
https://coverartarchive.org/release-group/f450a3d1-c7c4-3985-85f0-8bff98c63e17/front-500
https://coverartarchive.org/release-group/9cb50ffe-c5cf-338d-8833-f5fc5572f45f/front-500
https://upload.wikimedia.org/wikipedia/en/e/e9/Kryptonite_%28DC_Comics%29.jpg
https://coverartarchive.org/release-group/122990dd-643d-4e4e-bc13-a56318d6431b/front-500
https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/M0354_000727-005_1.jpg/960px-M0354_000727-005_1.jpg
https://coverartarchive.org/release-group/9f28cd3f-43e3-3b54-a3c5-e861d7e6958a/front-500
https://coverartarchive.org/release-group/a2a0757f-46b4-47d1-b152-e0d34b6f7253/front-500
https://coverartarchive.org/release-group/7257d8e2-807d-3597-991f-2e33931147c6/front-500
https://coverartarchive.org/release-group/572737e3-02d9-346e-be7d-dc13b5a2ba06/front-500
https://coverartarchive.org/release-group/e9d0e4f7-b0db-4cf0-be3d-3d0fbac5a878/front-500
https://upload.wikimedia.org/wikipedia/en/1/14/Bye_Bye_Bye.png
https://coverartarchive.org/release-group/f38ae9f7-30a2-37e0-9046-f69b39f64c55/front-500
https://upload.wikimedia.org/wikipedia/en/3/30/Beyonce_-_Crazy_in_Love_%28single%29.png
https://upload.wikimedia.org/wikipedia/en/4/4e/Since_U_Been_Gone.jpg
https://coverartarchive.org/release-group/45da9521-164f-3ab7-aeca-ae7afae26f46/front-500
https://upload.wikimedia.org/wikipedia/en/2/29/Blink-182_-_All_the_Small_Things_cover.jpg
https://coverartarchive.org/release-group/7aa5a01a-711e-34c5-9240-f96649db4321/front-500
https://upload.wikimedia.org/wikipedia/en/2/28/SexyBack.png
https://upload.wikimedia.org/wikipedia/en/8/82/GetThePartyStartedSingle.jpg
https://coverartarchive.org/release-group/1ad545e6-193a-3f3e-be20-e99dbd2d5017/front-500
https://coverartarchive.org/release-group/881c6548-d694-3f54-a01e-c74d1f837af7/front-500
https://coverartarchive.org/release-group/6dbcdc60-b6d0-3a0f-836e-89c568813b36/front-500
https://coverartarchive.org/release-group/b5e845f9-cd59-340d-afb8-ca07bb43652f/front-500
https://upload.wikimedia.org/wikipedia/en/a/a0/Use_Somebody.jpg
https://coverartarchive.org/release-group/39e68c14-7e31-33e7-9caf-e60058732adf/front-500
https://coverartarchive.org/release-group/135b34b9-835f-3d1c-870c-bca3d0dcede6/front-500
https://coverartarchive.org/release-group/5ba0be92-dfbc-344f-a354-04d246258e1e/front-500$im$, E'\n'),
  array_fill('nonfree'::text, array[40]));

-- ── Breakfast Cereals · 36 items
select public.df20_seed_category(
  'Breakfast Cereals',
  string_to_array($it$Life
Puffins
Corn Flakes
Grape-Nuts
Honeycomb
Boo Berry
Peanut Butter Crunch
Lucky Charms
Multi Grain Cheerios
Froot Loops
Rice Krispies
Shredded Wheat
Honey Smacks
Cinnamon Toast Crunch
Frosted Flakes
Fruity Pebbles
Cookie Crisp
Cocoa Puffs
Honey Nut Cheerios
Wheaties
Apple Jacks
Special K
Corn Pops
Rice Chex
Frosted Mini-Wheats
Golden Crisp
Raisin Nut Bran
Alpha-Bits
Reese's Puffs
Golden Grahams
French Toast Crunch
Honey Bunches of Oats
Waffle Crisp
Cracklin' Oat Bran
Kix
Oatmeal Crisp$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/6/63/Life_cereal_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Papageitaucher_Fratercula_arctica.jpg/960px-Papageitaucher_Fratercula_arctica.jpg
https://upload.wikimedia.org/wikipedia/en/d/d1/Kellogg%27s_Corn_Flakes.png
https://upload.wikimedia.org/wikipedia/commons/f/fc/Grape_nuts_logo.png
https://upload.wikimedia.org/wikipedia/commons/a/a4/Honeycomb_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/3/33/Count-Chocula-Box-Small.jpg
https://upload.wikimedia.org/wikipedia/commons/d/d4/Capcrunch_textlogo.png
https://upload.wikimedia.org/wikipedia/commons/6/69/Lucky_charms_brand_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Cheerios_with_Happy_Heart_Shapes.jpg/960px-Cheerios_with_Happy_Heart_Shapes.jpg
https://upload.wikimedia.org/wikipedia/en/9/9d/Frootloops_brand_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Rice_Krispies_logo.svg/960px-Rice_Krispies_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Two_shredded_wheat.jpg/960px-Two_shredded_wheat.jpg
https://upload.wikimedia.org/wikipedia/commons/0/0e/Honeymacks_brand_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Cinnamon_toastcrunch_logo.png/960px-Cinnamon_toastcrunch_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Frostedflakes_brand_logo.png/960px-Frostedflakes_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/6/62/Pebbles_cereal_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/5/58/Cookie_Crisp_USA_logo.png
https://upload.wikimedia.org/wikipedia/en/f/ff/Cocoa_Puffs_logo.png
https://upload.wikimedia.org/wikipedia/en/c/c4/Honey_nut_cheerios_%28revised%29.jpg
https://upload.wikimedia.org/wikipedia/en/5/51/Wheaties_logo.png
https://upload.wikimedia.org/wikipedia/en/4/41/Kellogg%27s_Apple_Jacks.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Specialk_brand_logo.png/960px-Specialk_brand_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Corn_Pops_logo.svg/960px-Corn_Pops_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/4/4c/Corn-chex-box.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Frosted_Mini-Wheats_logo.svg/960px-Frosted_Mini-Wheats_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/6/6f/Golden_crisp_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Raisin-Bran-Bowl.jpg/960px-Raisin-Bran-Bowl.jpg
https://upload.wikimedia.org/wikipedia/en/6/67/Alpha_bits_brand_logo.png
https://upload.wikimedia.org/wikipedia/commons/5/59/Reeses_Puffs_logo.png
https://upload.wikimedia.org/wikipedia/en/9/9d/Golden_Grahams_logo.png
https://upload.wikimedia.org/wikipedia/en/2/2f/French-Toast-Crunch-Box.jpg
https://upload.wikimedia.org/wikipedia/en/0/08/Honey_bunches_oat_logo.png
https://upload.wikimedia.org/wikipedia/commons/d/de/Waffle_crisp_logo.png
https://upload.wikimedia.org/wikipedia/commons/7/74/Cracklin_oatbran_logo.png
https://upload.wikimedia.org/wikipedia/en/7/7e/Kix_cereal.png
https://upload.wikimedia.org/wikipedia/en/e/e0/Oatmeal_Crisp.png$im$, E'\n'),
  array_fill('nonfree'::text, array[36]));

-- ── Soft Drinks · 35 items
select public.df20_seed_category(
  'Soft Drinks',
  string_to_array($it$7 Up
A&W Root Beer
Barq's
Big Red
Canada Dry Ginger Ale
Cheerwine
Cherry Coke
Coca-Cola
Code Red
Coke Zero
Cream Soda
Diet Coke
Diet Dr Pepper
Diet Pepsi
Faygo
Fresca
Ginger Beer
Inca Kola
Irn-Bru
Jarritos
Mello Yello
Mountain Dew
Moxie
Mug Root Beer
Orange Crush
Pepsi
RC Cola
Root Beer Float
Schweppes
Shasta
Sprite
Sprite Zero
Vanilla Coke
Vernors
Wild Cherry Pepsi$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/7up_1.jpg/960px-7up_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/A%26W_Root_Beer_logo.svg/960px-A%26W_Root_Beer_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Barq%27s_wordmark.svg/960px-Barq%27s_wordmark.svg.png
https://commons.wikimedia.org/wiki/Special:FilePath/Big%20Red%20soda%20four-pack.jpg?width=800
https://upload.wikimedia.org/wikipedia/en/a/a6/New_Canada_Dry_US_Logo_2024.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Cheerwine_Logo%2C_January_2018.svg/960px-Cheerwine_Logo%2C_January_2018.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Coca-Cola_Cherry_Poland.png/960px-Coca-Cola_Cherry_Poland.png
https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Coca_Cola_Flasche_-_Original_Taste.jpg/960px-Coca_Cola_Flasche_-_Original_Taste.jpg
https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Mountain_Dew_Code_Red_logo.svg/960px-Mountain_Dew_Code_Red_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Coca_cola_zero_1.jpg/960px-Coca_cola_zero_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Drink_Hand_crafted_cream_soda_%2818705306063%29.jpg/960px-Drink_Hand_crafted_cream_soda_%2818705306063%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Diet_coke_1.jpg/960px-Diet_coke_1.jpg
https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Dr_Pepper_modern.svg/960px-Dr_Pepper_modern.svg.png
https://upload.wikimedia.org/wikipedia/commons/3/36/Diet_pepsi_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Faygo_logo.svg/960px-Faygo_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/b/be/Fresca2005.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Ginger_beer_bottle_assortment.jpg/960px-Ginger_beer_bottle_assortment.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/IncaKolaBottleGlass.jpg/960px-IncaKolaBottleGlass.jpg
https://upload.wikimedia.org/wikipedia/en/9/9d/Irn-Bru_logo.png
https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Jarritos_Logo.svg/960px-Jarritos_Logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/d/d3/Logo_mello_yello.png
https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Mountain_Dew_2025_logo.svg/960px-Mountain_Dew_2025_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Moxie_soda%2C_full_logo.svg/960px-Moxie_soda%2C_full_logo.svg.png
https://upload.wikimedia.org/wikipedia/en/0/05/Mug_root_beer_logo.png
https://upload.wikimedia.org/wikipedia/commons/6/6a/Crush_Soda_Logo_New.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Pepsi_2023.svg/960px-Pepsi_2023.svg.png
https://upload.wikimedia.org/wikipedia/commons/0/07/RC_Cola_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Soda_jerk_NYWTS.jpg/960px-Soda_jerk_NYWTS.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Schweppes_wordmark.svg/960px-Schweppes_wordmark.svg.png
https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Shasta_%28soft_drink%29_logo.svg/960px-Shasta_%28soft_drink%29_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Sprite_lemon_lime_1.jpg/960px-Sprite_lemon_lime_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Sprite_Zero_Sugar_1.jpg/960px-Sprite_Zero_Sugar_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Vanilla_Coca-Cola.jpg/960px-Vanilla_Coca-Cola.jpg
https://upload.wikimedia.org/wikipedia/en/6/68/Vernorslogo.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Pepsi_wild_cherry_bottle.jpg/960px-Pepsi_wild_cherry_bottle.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[35]));

-- ── Ice Cream Flavors · 30 items
select public.df20_seed_category(
  'Ice Cream Flavors',
  string_to_array($it$Superman
Tiramisu
Banana
Coffee
Mango
Strawberry
Peach
Coconut
Pistachio
Chocolate
Cannoli
Vanilla
Blackberry
S'mores
Pumpkin
Cheesecake
Green Tea
Spumoni
Butterscotch
Cotton Candy
Eggnog
Bubblegum
Birthday Cake
Cookies and Cream
Mint Chocolate Chip
Butter Pecan
Neapolitan
Black Raspberry
Peanut Butter Cup
Praline$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Ice_cream_dish_-_superman_flavor.jpg/960px-Ice_cream_dish_-_superman_flavor.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Tiramisu_-_Raffaele_Diomede.jpg/960px-Tiramisu_-_Raffaele_Diomede.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Banana_split_1.jpg/960px-Banana_split_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Vegan_Hazelnut_Coffee_Ice_Cream_%285013027435%29.jpg/960px-Vegan_Hazelnut_Coffee_Ice_Cream_%285013027435%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/960px-Mangos_-_single_and_halved.jpg
https://upload.wikimedia.org/wikipedia/commons/d/da/Strawberry_ice_cream_cone_%285076899310%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Chicken_and_waffles_with_peaches_and_cream.jpg/960px-Chicken_and_waffles_with_peaches_and_cream.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg/960px-Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Glace_%C3%A0_la_pistache-Lipari.jpg/960px-Glace_%C3%A0_la_pistache-Lipari.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Chocolate_chip_cookie_dough_ice_cream_with_orange_spoon.jpg/960px-Chocolate_chip_cookie_dough_ice_cream_with_orange_spoon.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cannoli_siciliani_al_Caff%C3%A8_Impero%2C_ad_Alcamo.jpg/960px-Cannoli_siciliani_al_Caff%C3%A8_Impero%2C_ad_Alcamo.jpg
https://upload.wikimedia.org/wikipedia/commons/f/f3/Vanilla_Ice_Cream_Cone_at_Camp_Manitoulin.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ripe%2C_ripening%2C_and_green_blackberries.jpg/960px-Ripe%2C_ripening%2C_and_green_blackberries.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Smores-Microwave.jpg/960px-Smores-Microwave.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Pumpkin_Spice_%2848986157673%29_cropped.png/960px-Pumpkin_Spice_%2848986157673%29_cropped.png
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/960px-Baked_cheesecake_with_raspberries_and_blueberries.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Matcha_ice_cream_001.jpg/960px-Matcha_ice_cream_001.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Spumonipic.jpg/960px-Spumonipic.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Butterscotch-Candies.jpg/960px-Butterscotch-Candies.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG/960px-Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG
https://upload.wikimedia.org/wikipedia/commons/a/a7/Eggnog2.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Blowing_bubble_gum.jpg/960px-Blowing_bubble_gum.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Delicious_Birthday_Cake_%2814346969741%29.jpg/960px-Delicious_Birthday_Cake_%2814346969741%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cookies_and_cream.JPG/960px-Cookies_and_cream.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/2020-04-27_18_23_07_A_spoonful_of_Friendly%27s_Mint_Chocolate_Chip_Ice_Cream_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg/960px-2020-04-27_18_23_07_A_spoonful_of_Friendly%27s_Mint_Chocolate_Chip_Ice_Cream_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg
https://upload.wikimedia.org/wikipedia/commons/e/ed/Butter_pecan_caramel_ice_cream.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Neapolitan.jpg/960px-Neapolitan.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Colorful_Black_Raspberry_Ice_Cream_Cone_%282420648653%29.jpg/960px-Colorful_Black_Raspberry_Ice_Cream_Cone_%282420648653%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Reese%27s_logo.svg/960px-Reese%27s_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Brittle_made_of_Hazelnuts.jpg/960px-Brittle_made_of_Hazelnuts.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[30]));

-- ── Pizza Toppings · 29 items
select public.df20_seed_category(
  'Pizza Toppings',
  string_to_array($it$Anchovies
Arugula
Bacon
Banana Peppers
Blue Cheese
Broccoli
Buffalo Sauce
Chorizo
Eggplant
Feta
Fried Egg
Goat Cheese
Grilled Chicken
Ground Beef
Ham
Italian Sausage
Jalapenos
Meatballs
Mushrooms
Onions
Pepperoni
Pesto
Pineapple
Prosciutto
Ricotta
Salami
Spinach
Truffle Oil
Zucchini$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Acciugaio_in_Valle_Maira.jpg/960px-Acciugaio_in_Valle_Maira.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Eruca_sativa_sl11.jpg/960px-Eruca_sativa_sl11.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Bacon_sandwich_%2814450831119%29.jpg/960px-Bacon_sandwich_%2814450831119%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Banana_Peppers_%28Armenia%29.jpg/960px-Banana_Peppers_%28Armenia%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Bleu_au_lait_de_ch%C3%A8vre.jpg/960px-Bleu_au_lait_de_ch%C3%A8vre.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Cream_of_broccoli_soup.jpg/960px-Cream_of_broccoli_soup.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Buffalo_wings-01.jpg/960px-Buffalo_wings-01.jpg
https://upload.wikimedia.org/wikipedia/commons/2/25/Chorizos_P6021974.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/960px-Solanum_melongena_24_08_2012_%281%29.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Feta_Cheese.jpg/960px-Feta_Cheese.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Fried_Egg_2.jpg/960px-Fried_Egg_2.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Plateau_3_horizontal.tif/lossy-page1-960px-Plateau_3_horizontal.tif.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/TenderGrill_2013.JPG/960px-TenderGrill_2013.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Hackfleisch-1.jpg/960px-Hackfleisch-1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Ham_%284%29.jpg/960px-Ham_%284%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Salsiccia_Italian_pork_sausage.jpg/960px-Salsiccia_Italian_pork_sausage.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Immature_jalapeno_capsicum_annuum_var_annuum.jpeg/960px-Immature_jalapeno_capsicum_annuum_var_annuum.jpeg
https://upload.wikimedia.org/wikipedia/commons/f/fc/Porcupine_meatballs.jpg
https://upload.wikimedia.org/wikipedia/commons/5/59/Baby_bella_mushrooms_being_saut%C3%A9ed.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/960px-Mixed_onions.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Pepperoni_Pizza_%2829204589095%29.jpg/960px-Pepperoni_Pizza_%2829204589095%29.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/BasilPesto.JPG/960px-BasilPesto.JPG
https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/960px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Prosciutto_di_Parma%2C_ham_producing.jpg/960px-Prosciutto_di_Parma%2C_ham_producing.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Ricotte_fresche.jpg/960px-Ricotte_fresche.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Salame_di_Sauris.jpg/960px-Salame_di_Sauris.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Spinach_%26_artichoke_dip.jpg/960px-Spinach_%26_artichoke_dip.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Huile_d%27olive_de_Nyons_1.jpg/960px-Huile_d%27olive_de_Nyons_1.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/960px-CSA-Striped-Zucchini.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[29]));

-- ── Halloween Candy · 36 items
select public.df20_seed_category(
  'Halloween Candy',
  string_to_array($it$Milky Way
Hershey's Milk Chocolate
Peanut M&M's
Snickers
Kit Kat
Airheads
Reese's Peanut Butter Cups
Smarties
Twix
Swedish Fish
Werther's Original
Butterfinger
Tootsie Roll
Candy Corn
Baby Ruth
Jolly Rancher
Sour Patch Kids
Mike and Ike
Nestle Crunch
Tootsie Pops
Milk Duds
Pixy Stix
Hershey's Kisses
Rolo
Charleston Chew
Almond Joy
Whoppers
Dum Dums
Sweet Tarts
Hot Tamales
100 Grand
Bit-O-Honey
Laffy Taffy
York Peppermint Pattie
Fun Dip
Now and Later$it$, E'\n'),
  string_to_array($im$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Milky-Way-Bars-USUK-Whole.jpg/960px-Milky-Way-Bars-USUK-Whole.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hershey_Factory.jpg/960px-Hershey_Factory.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Plain-M%26Ms-Pile.jpg/960px-Plain-M%26Ms-Pile.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Snickers-broken.png/960px-Snickers-broken.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Japanese_kit_Kat_varieties.jpg/960px-Japanese_kit_Kat_varieties.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Airheads_candy_flavors.jpg/960px-Airheads_candy_flavors.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Reese%27s_logo.svg/960px-Reese%27s_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Smarties-UK-Candies_%28cropped%29.jpg/960px-Smarties-UK-Candies_%28cropped%29.jpg
https://upload.wikimedia.org/wikipedia/commons/4/43/Twix_brand_logo.png
https://upload.wikimedia.org/wikipedia/en/6/6d/Swedish-Fish-Wrapper-Small.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/An_Open_Bag_of_Werther%27s_Original.jpg/960px-An_Open_Bag_of_Werther%27s_Original.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Butterfinger-broken.JPG?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Tootsie-Roll-WU.jpg/960px-Tootsie-Roll-WU.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Candy-Corn.jpg/960px-Candy-Corn.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Baby-Ruth-Split.jpg/960px-Baby-Ruth-Split.jpg
https://upload.wikimedia.org/wikipedia/commons/a/ae/Jolly_rancher_logo.png
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Sour-Patch-Kids.jpg/960px-Sour-Patch-Kids.jpg
https://upload.wikimedia.org/wikipedia/en/8/87/New_Mike_and_Ike_Original_Fruits_packaging_launched_in_2013.png
https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Nestl%C3%A9_Crunch.jpg/960px-Nestl%C3%A9_Crunch.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Tootsie_Pops_logo.svg/960px-Tootsie_Pops_logo.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/MilkDudsinawhitebowl.jpg/960px-MilkDudsinawhitebowl.jpg
https://upload.wikimedia.org/wikipedia/en/1/13/PixyStixProduct.jpg
https://upload.wikimedia.org/wikipedia/commons/c/c5/Hershey%27s_KISSES_Chocolate_Flavors_Written_on_Paper_Plume.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Rolo-Candies-US.jpg/960px-Rolo-Candies-US.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Charleston-Chew-Split.jpg?width=800
https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Almond-joy-broken.jpg/960px-Almond-joy-broken.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Whoppers.jpg/960px-Whoppers.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Dum_Dums_Lollipops.jpg/960px-Dum_Dums_Lollipops.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Nestle-SweeTarts-Candies.jpg/960px-Nestle-SweeTarts-Candies.jpg
https://upload.wikimedia.org/wikipedia/en/f/fc/Illustration_of_Hot_Tamales_candy_packaging_in_use_since_2013.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Candy-100Grand-Broken.jpg/960px-Candy-100Grand-Broken.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/BOH_ind_wrapped_SINGLE_NEW.jpg/960px-BOH_ind_wrapped_SINGLE_NEW.jpg
https://commons.wikimedia.org/wiki/Special:FilePath/Laffy-Taffy-Slab.jpg?width=800
https://upload.wikimedia.org/wikipedia/commons/4/4f/York_peppermint_logo.png
https://upload.wikimedia.org/wikipedia/en/6/6f/Fun-Dip-Wrapper-Small.jpg
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Now-and-Laters.jpg/960px-Now-and-Laters.jpg$im$, E'\n'),
  array_fill('nonfree'::text, array[36]));

do $$
declare c text; v_total int; v_imgs int; v_distinct int;
  v_cats text[] := array['US States', 'NFL Teams', 'NBA Teams', 'MLB Teams', 'Superheroes', 'Movie Villains', 'Disney Animated Movies', 'TV Sitcoms', 'Video Game Franchises', 'Board Games', 'Dog Breeds', '90s Songs', '2000s Songs', 'Breakfast Cereals', 'Soft Drinks', 'Ice Cream Flavors', 'Pizza Toppings', 'Halloween Candy'];
begin
  foreach c in array v_cats loop
    select count(*), count(i.image_url), count(distinct i.image_url)
      into v_total, v_imgs, v_distinct
      from public.category_library_items i
      join public.category_library l on l.id = i.library_id
     where l.name_norm = public.df20_norm_category(c);
    if v_total < 24 then raise exception 'DF20_LIB_TOO_SMALL: % has %', c, v_total; end if;
    if v_imgs < v_total then raise exception 'DF20_LIB_MISSING_IMAGES: % of % in %', v_total - v_imgs, v_total, c; end if;
    if v_distinct < v_total then raise exception 'DF20_LIB_DUPLICATE_IMAGES: % shares %', c, v_total - v_distinct; end if;
    raise notice '%: % items, % distinct pictures', c, v_total, v_distinct;
  end loop;
end $$;
